// Web/roomkit/vue3/RoomKit/components/PasswordDialogH5/index.vue
<template>
  <TUIDialog
    v-model:visible="visible"
    :title="t('Room.EnterPassword')"
    :show-close="false"
    :modal="false"
    @confirm="handleConfirm"
    @cancel="handleCancel"
  >
    <TUIInput
      v-model="password"
      type="number"
      show-password
      max-length="6"
      :placeholder="t('Room.EnterPasswordPlaceholder')"
      @keyup.enter="handleConfirm"
    />
  </TUIDialog>
</template>

<script lang="ts" setup>
import { ref, watch } from 'vue';
import { TUIDialog, TUIInput, TUIToast, useUIKit } from '@tencentcloud/uikit-base-component-vue3';
import { useRoomState } from 'tuikit-atomicx-vue3/room';

interface Props {
  modelValue: boolean;
  roomId: string;
}

interface Emits {
  (e: 'update:modelValue', value: boolean): void;
  (e: 'success', data: { roomId: string; password: string }): void;
  (e: 'cancel'): void;
  (e: 'error', error: any): void;
}

const props = defineProps<Props>();
const emit = defineEmits<Emits>();

const { t } = useUIKit();
const { joinRoom } = useRoomState();

const visible = ref(false);
const password = ref('');
const isJoining = ref(false);

watch(() => props.modelValue, (val) => {
  visible.value = val;
});

watch(visible, (val) => {
  emit('update:modelValue', val);
  if (!val) {
    password.value = '';
  }
});

const handleConfirm = async () => {
  if (!password.value) {
    TUIToast.error({ message: t('Room.EnterPassword') });
    return;
  }

  if (isJoining.value) {
    return;
  }

  try {
    isJoining.value = true;
    await joinRoom({
      roomId: props.roomId,
      password: password.value,
    });

    visible.value = false;
    password.value = '';
    emit('success', { roomId: props.roomId, password: password.value });
  } catch (error) {
    console.error('Failed to join room with password:', error);
    emit('error', error);
  } finally {
    isJoining.value = false;
  }
};

const handleCancel = () => {
  visible.value = false;
  password.value = '';
  emit('cancel');
};
</script>

<style lang="scss" scoped>
.button-container {
    display: flex;
    gap: 12px;
    width: 100%;
    justify-content: center;
    padding: 20px;
}
</style>

// Web/roomkit/react/RoomKit/components/PasswordDialogH5/PasswordDialogH5.tsx
import { useEffect, useState } from 'react';
import type { KeyboardEvent } from 'react';
import {
  Dialog,
  Input,
  Toast,
  useUIKit,
} from '@tencentcloud/uikit-base-component-react';
import { useRoomState } from 'tuikit-atomicx-react/room';

export interface PasswordDialogH5Props {
  visible: boolean;
  roomId: string;
  onCancel?: () => void;
  onError?: (error: unknown) => void;
  onSuccess?: (data: { roomId: string; password: string }) => void;
  onVisibleChange?: (visible: boolean) => void;
}

// Vue reference: PasswordDialogH5/index.vue (102 lines).
export function PasswordDialogH5({
  visible,
  roomId,
  onCancel,
  onError,
  onSuccess,
  onVisibleChange,
}: PasswordDialogH5Props) {
  const { t } = useUIKit();
  const { joinRoom } = useRoomState();

  const [password, setPassword] = useState('');
  const [isJoining, setIsJoining] = useState(false);

  useEffect(() => {
    if (!visible) {
      setPassword('');
    }
  }, [visible]);

  const closeDialog = () => {
    onVisibleChange?.(false);
  };

  const handleConfirm = async () => {
    if (!password) {
      Toast.error({ message: t('Room.EnterPassword') });
      return;
    }
    if (isJoining) {
      return;
    }
    try {
      setIsJoining(true);
      await joinRoom({ roomId, password });
      closeDialog();
      onSuccess?.({ roomId, password });
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error('Failed to join room with password:', error);
      onError?.(error);
    } finally {
      setIsJoining(false);
    }
  };

  const handleCancel = () => {
    if (isJoining) {
      return;
    }
    closeDialog();
    onCancel?.();
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    if (e.key === 'Enter') {
      e.preventDefault();
      handleConfirm();
    }
  };

  return (
    <Dialog
      visible={visible}
      title={t('Room.EnterPassword')}
      showClose={false}
      modal={false}
      confirmDisabled={isJoining}
      cancelDisabled={isJoining}
      onConfirm={() => handleConfirm()}
      onCancel={handleCancel}
    >
      <Input
        type="number"
        value={password}
        showPassword
        maxLength={6}
        disabled={isJoining}
        placeholder={t('Room.EnterPasswordPlaceholder')}
        onChange={e => setPassword(e.target.value)}
        onKeyDown={handleKeyDown}
      />
    </Dialog>
  );
}
