// Web/roomkit/vue3/RoomKit/components/CameraButtonH5/index.vue
<template>
  <div
    v-click-outside="handleHideVideoSettingTab"
    class="video-control-container"
  >
    <icon-button-h5
      :style="props.customStyle"
      :title="title"
      :has-more="true"
      :disabled="isCameraDisabled"
      @click="handleClickIcon"
    >
      <div class="video-icon-container">
        <template v-if="!currentRoom">
          <IconCameraOn v-if="isCameraTesting" size="24" />
          <IconCameraOff v-else size="24" />
        </template>
        <template v-else>
          <IconCameraOn
            v-if="cameraStatus === DeviceStatus.On"
            size="24"
          />
          <IconCameraOff v-else size="24" />
        </template>
        <IconUnSupport
          v-if="hasNotSupportError"
          class="un-support-icon"
          size="14"
        />
      </div>
    </icon-button-h5>
  </div>
</template>

<script setup lang="ts">
import type { Ref } from 'vue';
import { ref, computed } from 'vue';
import {
  TUIToast,
  IconCameraOn,
  IconCameraOff,
  IconUnSupport,
  useUIKit,
} from '@tencentcloud/uikit-base-component-vue3';

import { useDeviceState, useRoomState, DeviceStatus, useRoomParticipantState, DeviceError, DeviceType, RoomParticipantRole } from 'tuikit-atomicx-vue3/room';
import { conference } from '../../adapter/conference';
import { InterceptorAction } from '../../adapter/type';
import { handleMediaCaptureError } from '../../hooks/useMediaCaptureError';
import IconButtonH5 from '../base/IconButtonH5.vue';
import vClickOutside from '../base/vClickOutside';

interface Props {
  cameraTestContainer?: HTMLDivElement | string;
  showDescription?: boolean;
  customStyle?: Record<string, string>;
}

const props = withDefaults(defineProps<Props>(), {
  showDescription: true,
  customStyle: () => ({}),
});

const { t } = useUIKit();
const { cameraStatus, cameraLastError, isCameraTesting, startCameraTest, stopCameraTest, openLocalCamera, closeLocalCamera } = useDeviceState();
const { currentRoom } = useRoomState();
const { localParticipant } = useRoomParticipantState();

const showVideoSettingTab: Ref<boolean> = ref(false);
const isProcessing = ref(false);

const title = computed(() => {
  if (!props.showDescription) {
    return '';
  }
  if (!currentRoom.value) {
    return isCameraTesting.value ? t('Camera.Stop') : t('Camera.Start');
  }
  return cameraStatus.value === DeviceStatus.On ? t('Camera.Stop') : t('Camera.Start');
});

const isCameraDisabled = computed(() => {
  if (localParticipant.value?.role === RoomParticipantRole.Owner || localParticipant.value?.role === RoomParticipantRole.Admin) {
    return false;
  }
  if (cameraStatus.value === DeviceStatus.On) {
    return false;
  }
  return currentRoom.value?.isAllCameraDisabled;
});

const hasNotSupportError = computed(() => cameraLastError.value !== DeviceError.NoError);

async function handleClickIcon() {
  if (isProcessing.value) {
    return;
  }
  isProcessing.value = true;
  try {
    if (isCameraDisabled.value) {
      TUIToast.warning({
        message: t('Camera.Disabled'),
      });
      return;
    }
    if (!currentRoom.value && props.cameraTestContainer) {
      if (isCameraTesting.value) {
        await stopCameraTest();
      } else {
        await startCameraTest({ view: props.cameraTestContainer });
      }
      return;
    }
    if (localParticipant.value?.cameraStatus === DeviceStatus.On) {
      await conference.executeInterceptor(InterceptorAction.CloseCamera, async () => {
        await closeLocalCamera();
      });
    } else {
      await conference.executeInterceptor(InterceptorAction.OpenCamera, async () => {
        await openLocalCamera();
      });
    }
  } catch (error: any) {
    handleMediaCaptureError({ error, deviceType: DeviceType.Camera });
  } finally {
    isProcessing.value = false;
  }
}

function handleHideVideoSettingTab() {
  if (showVideoSettingTab.value) {
    showVideoSettingTab.value = false;
  }
}
</script>

<style lang="scss" scoped>
$videoTabWidth: 305px;

.video-icon-container {
  position: relative;
}

.un-support-icon {
  position: absolute;
  bottom: 1px;
  right: 1px;
}

.video-control-container {
  position: relative;
  display: flex;

  .video-tab {
    position: absolute;
    bottom: calc(100% + 12px);
    left: -5px;
    width: $videoTabWidth;
    box-sizing: border-box;
    padding: 20px 20px 24px;
    box-shadow:
      0 2px 4px -3px var(--uikit-color-black-8),
      0 6px 10px 1px var(--uikit-color-black-8),
      0 3px 14px 2px var(--uikit-color-black-8);
    border-radius: 8px;
    background-color: var(--bg-color-dialog);

    &::before {
      position: absolute;
      bottom: -10px;
      left: 30px;
      content: '';
      border-right: 5px solid transparent;
      border-bottom: 5px solid transparent;
      border-left: 5px solid transparent;
      border-top: 5px solid var(--bg-color-dialog);
    }
  }
}
</style>

// Web/roomkit/react/RoomKit/components/CameraButtonH5/CameraButtonH5.tsx
import type { CSSProperties } from 'react';
import { useState } from 'react';
import {
  IconCameraOff,
  IconCameraOn,
  IconUnSupport,
  Toast,
  useUIKit,
} from '@tencentcloud/uikit-base-component-react';
import {
  DeviceError,
  DeviceStatus,
  DeviceType,
  RoomParticipantRole,
  useDeviceState,
  useRoomParticipantState,
  useRoomState,
} from 'tuikit-atomicx-react/room';
import { conference } from '../../adapter/conference';
import { InterceptorAction } from '../../adapter/type';
import { handleMediaCaptureError } from '../../hooks/useMediaCaptureError';
import { IconButtonH5 } from '../base/IconButtonH5';
import styles from './CameraButtonH5.module.scss';

export interface CameraButtonH5Props {
  cameraTestContainer?: HTMLDivElement | string;
  showDescription?: boolean;
  customStyle?: CSSProperties;
  /**
   * Force-render the "permission denied" red-slash badge. Set by parent views
   * that listen to TUIRoomEvents.onError -1101 out-of-band, since atomicx's
   * cameraLastError only reflects promise rejections and misses the async
   * onError channel used when the browser rejects camera permission.
   */
  hasPermissionError?: boolean;
  /** Fired when the user taps the button, so the parent can clear its denial flag. */
  onRetryPermission?: () => void;
}

export function CameraButtonH5({
  cameraTestContainer,
  showDescription = true,
  customStyle,
  hasPermissionError = false,
  onRetryPermission,
}: CameraButtonH5Props) {
  const { t } = useUIKit();
  const {
    cameraStatus,
    cameraLastError,
    isCameraTesting,
    startCameraTest,
    stopCameraTest,
    openLocalCamera,
    closeLocalCamera,
  } = useDeviceState();
  const { currentRoom } = useRoomState();
  const { localParticipant } = useRoomParticipantState();

  const [isProcessing, setIsProcessing] = useState(false);

  const isOwnerOrAdmin =
    localParticipant?.role === RoomParticipantRole.Owner ||
    localParticipant?.role === RoomParticipantRole.Admin;
  const isCameraOn = cameraStatus === DeviceStatus.On;
  const isCameraDisabled =
    !isOwnerOrAdmin && !isCameraOn && Boolean(currentRoom?.isAllCameraDisabled);

  const resolveTitle = (): string => {
    if (!showDescription) return '';
    if (!currentRoom) {
      return isCameraTesting ? t('Camera.Stop') : t('Camera.Start');
    }
    return isCameraOn ? t('Camera.Stop') : t('Camera.Start');
  };
  const title = resolveTitle();

  const hasNotSupportError = cameraLastError !== DeviceError.NoError;

  const handleClickIcon = async () => {
    if (isProcessing) return;
    setIsProcessing(true);
    // Reset the parent-tracked denial flag so the red-slash badge disappears
    // while the browser re-prompts. If the user denies again, the onError
    // handler in PreviewView will re-set it.
    onRetryPermission?.();
    try {
      if (isCameraDisabled) {
        Toast.warning({ message: t('Camera.Disabled') });
        return;
      }
      if (!currentRoom && cameraTestContainer) {
        if (isCameraTesting) {
          await stopCameraTest();
        } else {
          await startCameraTest({ view: cameraTestContainer });
        }
        return;
      }
      if (localParticipant?.cameraStatus === DeviceStatus.On) {
        await conference.executeInterceptor(InterceptorAction.CloseCamera, async () => {
          await closeLocalCamera();
        });
      } else {
        await conference.executeInterceptor(InterceptorAction.OpenCamera, async () => {
          await openLocalCamera();
        });
      }
    } catch (error) {
      handleMediaCaptureError({ error, deviceType: DeviceType.Camera });
    } finally {
      setIsProcessing(false);
    }
  };

  // Pre-room preview branch adds `!hasNotSupportError` on top of the Vue
  // reference: if camera capture failed (permission denied, occupied, etc.)
  // the button shouldn't render "On" even though atomicx may briefly leave
  // `isCameraTesting=true` from the still-pending success path. Vue H5 relies
  // on Vue's proxy reactivity to reconcile faster; React's valtio snapshot
  // needs this guard to avoid a visibly wrong Camera-On icon during the
  // error window.
  const showCameraOn = currentRoom
    ? isCameraOn
    : (isCameraTesting && !hasNotSupportError);

  const showUnSupportBadge = hasNotSupportError || hasPermissionError;

  return (
    <div className={styles.videoControl}>
      <IconButtonH5
        title={title}
        disabled={isCameraDisabled}
        customStyle={customStyle}
        onClick={handleClickIcon}
      >
        <div className={styles.videoIconContainer}>
          {showCameraOn ? (
            <IconCameraOn size="24" />
          ) : (
            <IconCameraOff size="24" />
          )}
          {showUnSupportBadge && (
            <IconUnSupport className={styles.unSupportIcon} size="14" />
          )}
        </div>
      </IconButtonH5>
    </div>
  );
}
