// Web/roomkit/react/RoomKit/components/RoomParticipantList/ParticipantActionH5.tsx
import {
  Popup,
  useUIKit,
} from '@tencentcloud/uikit-base-component-react';
import { Avatar } from 'tuikit-atomicx-react/room';
import { useParticipantAction } from './useParticipantAction';
import { PopUpArrowDown } from '../base/PopUpArrowDown';
import styles from './ParticipantActionH5.module.scss';
import type { RoomParticipant } from 'tuikit-atomicx-react/room';

export interface ParticipantActionH5Props {
  visible: boolean;
  participant: RoomParticipant | null;
  onVisibleChange: (visible: boolean) => void;
}

// Vue reference: RoomParticipantList/ParticipantActionH5.vue (135 lines).
// Business logic (per-participant action list) reused from atomicx-react's
// shared `useParticipantAction` hook (same hook the PC ParticipantAction uses).
//
// `useParticipantAction` inside atomicx dereferences `targetParticipant.userId`
// unconditionally, so we only mount the inner component when a participant has
// actually been selected.
export function ParticipantActionH5(props: ParticipantActionH5Props) {
  if (!props.participant) {
    return null;
  }
  return <ParticipantActionH5Inner {...props} participant={props.participant} />;
}

function ParticipantActionH5Inner({
  visible,
  participant,
  onVisibleChange,
}: ParticipantActionH5Props & { participant: RoomParticipant }) {
  useUIKit();
  const { controlList } = useParticipantAction({ targetParticipant: participant });

  const title
    = participant.nameCard || participant.userName || participant.userId;

  const handleActionClick = (handler: () => void) => {
    handler();
    onVisibleChange(false);
  };

  return (
    <Popup visible={visible} onUpdateVisible={onVisibleChange}>
      <PopUpArrowDown onClick={() => onVisibleChange(false)} />
      <div className={styles.participantActionH5}>
        <div className={styles.header}>
          <Avatar src={participant.avatarUrl} />
          <span className={styles.headerTitle}>{title}</span>
        </div>
        {controlList.map((item) => {
          const IconComponent = item.icon;
          return (
            <div
              key={item.key}
              className={styles.actionItem}
              style={item.style}
              onClick={() => handleActionClick(item.handler)}
            >
              {IconComponent && (
                <IconComponent
                  size="20"
                  className={styles.actionIcon}
                />
              )}
              <span className={styles.actionText}>{item.label}</span>
            </div>
          );
        })}
      </div>
    </Popup>
  );
}

// Web/roomkit/vue3/RoomKit/components/RoomParticipantList/ParticipantActionH5.vue
<template>
  <TUIPopup
    :visible="visible"
    @update:visible="handleUpdateVisible"
  >
    <PopUpArrowDown @click="handleUpdateVisible(false)" />
    <div class="participant-action-h5">
      <div class="participant-action-h5-header">
        <Avatar :src="participant?.avatarUrl" />
        <span class="participant-action-h5-header-title">{{ title }}</span>
      </div>
      <div
        v-for="item in controlList"
        :key="item.key"
        class="action-item"
        :style="item?.style || {}"
        @click="handleActionClick(item.handler)"
      >
        <TUIIcon
          v-if="item?.icon"
          :icon="item?.icon"
          size="20"
          class="action-icon"
        />
        <span class="action-text">{{ item.label }}</span>
      </div>
    </div>
  </TUIPopup>
</template>

<script setup lang="ts">
import type { Ref } from 'vue';
import { computed, toRef } from 'vue';
import { useUIKit, TUIIcon, TUIPopup } from '@tencentcloud/uikit-base-component-vue3';
import { Avatar } from 'tuikit-atomicx-vue3/room';
import PopUpArrowDown from './PopUpArrowDown.vue';
import { useParticipantAction } from './useParticpantAction';
import type { RoomParticipant } from 'tuikit-atomicx-vue3/room';

defineOptions({
  name: 'ParticipantActionH5',
});

interface Props {
  visible: boolean;
  participant: RoomParticipant | null;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  'update:visible': [visible: boolean];
}>();

const { t } = useUIKit();

const title = computed(() => {
  if (!props.participant) {
    return t('ParticipantList.Operation');
  }
  const displayName = props.participant?.nameCard || props.participant?.userName || props.participant?.userId;
  return displayName;
});

const controlList = computed(() => {
  if (!props.participant) {
    return [];
  }
  const { controlList: list } = useParticipantAction({ targetParticipant: toRef(props, 'participant') as Ref<RoomParticipant> });

  return list.value;
});

const handleUpdateVisible = (value: boolean) => {
  emit('update:visible', value);
};

const handleActionClick = (handler: () => void) => {
  handler();
  emit('update:visible', false);
};
</script>

<style scoped lang="scss">
.participant-action-h5 {
  display: flex;
  flex-direction: column;
  padding: 12px 20px;
  -webkit-tap-highlight-color: transparent;

  .participant-action-h5-header {
    display: flex;
    align-items: center;
    gap: 12px;
    font-size: 16px;
    font-weight: 600;
    margin-bottom: 12px;

    .participant-action-h5-header-title {
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      min-width: 0;
    }
  }
}

.action-item {
  display: flex;
  align-items: center;
  cursor: pointer;
  transition: background 0.2s ease;
  gap: 12px;
  color: var(--text-color-secondary);
  font-size: 16px;
  font-weight: 400;
  border-bottom: 1px solid var(--stroke-color-secondary);
  padding: 16px 0;

  &:active {
    background: var(--list-color-hover);
  }

  .action-icon {
    flex-shrink: 0;
  }

  .action-text {
    flex: 1;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
}
</style>
