// Web/roomkit/react/RoomKit/components/RoomParticipantList/PendingParticipantItemH5.tsx
import { useEffect, useRef, useState } from 'react';
import { Button, Toast, useUIKit } from '@tencentcloud/uikit-base-component-react';
import {
  Avatar,
  RoomParticipantStatus,
  useRoomState,
} from 'tuikit-atomicx-react/room';
import styles from './PendingParticipantItemH5.module.scss';
import type { RoomParticipant } from 'tuikit-atomicx-react/room';

export interface PendingParticipantItemH5Props {
  userInfo: RoomParticipant;
}

// Vue reference: RoomParticipantList/PendingParticipantItemH5.vue (164 lines).
export function PendingParticipantItemH5({
  userInfo,
}: PendingParticipantItemH5Props) {
  const { t } = useUIKit();
  const { currentRoom, callUserToRoom } = useRoomState();

  const displayName = userInfo?.userName || userInfo?.userId;

  // Match Vue `watch(roomStatus)` without `immediate`: only react to status
  // transitions, not the value already present when the row mounts. Otherwise
  // opening「未进房」flashes「暂不入会」for leftover CallRejected members.
  const [showRejectedMessage, setShowRejectedMessage] = useState(false);
  const prevRoomStatusRef = useRef(userInfo.roomStatus);
  useEffect(() => {
    const prevStatus = prevRoomStatusRef.current;
    prevRoomStatusRef.current = userInfo.roomStatus;

    if (
      userInfo.roomStatus === RoomParticipantStatus.CallRejected
      && prevStatus !== RoomParticipantStatus.CallRejected
    ) {
      setShowRejectedMessage(true);
      const timer = window.setTimeout(() => setShowRejectedMessage(false), 3000);
      return () => window.clearTimeout(timer);
    }

    if (userInfo.roomStatus !== RoomParticipantStatus.CallRejected) {
      setShowRejectedMessage(false);
    }
    return undefined;
  }, [userInfo.roomStatus]);

  const handleInvite = async () => {
    if (!currentRoom?.roomId) {
      return;
    }
    try {
      await callUserToRoom({
        roomId: currentRoom.roomId,
        userIdList: [userInfo.userId],
        timeout: 60,
      });
      Toast.success({ message: t('ParticipantList.InviteSuccess') });
    } catch (error) {
      Toast.error({ message: t('ParticipantList.InviteFailed') });
      // eslint-disable-next-line no-console
      console.error('Failed to invite user to room:', error);
    }
  };

  return (
    <div className={styles.pendingParticipantItemH5}>
      <Avatar src={userInfo.avatarUrl} size={40} />
      <div className={styles.participantContent}>
        <div className={styles.userInfo}>
          <span className={styles.userName}>{displayName}</span>
          <div className={styles.statusContainer}>
            {showRejectedMessage && <span>{t('ParticipantList.NotJoin')}</span>}
            {userInfo.roomStatus === RoomParticipantStatus.InCalling
              ? (
                <span>{t('ParticipantList.Calling')}</span>
              )
              : (
                <Button type="primary" onClick={() => handleInvite()}>
                  {t('ParticipantList.Call')}
                </Button>
              )}
          </div>
        </div>
      </div>
    </div>
  );
}

// Web/roomkit/vue3/RoomKit/components/RoomParticipantList/PendingParticipantItemH5.vue
<template>
  <div
    :class="{ 'pending-participant-item-h5': true, 'hovered': isHovered }"
    @mouseenter="handleMouseEnter"
    @mouseleave="handleMouseLeave"
  >
    <Avatar :src="userInfo.avatarUrl" :size="40" />
    <div class="participant-content">
      <div class="user-info">
        <span class="user-name">{{ displayName }}</span>

        <div class="status-container">
          <span v-if="showRejectedMessage">{{ t('ParticipantList.NotJoin') }}</span>
          <span v-if="userInfo.roomStatus === RoomParticipantStatus.InCalling">{{ t('ParticipantList.Calling') }}</span>
          <TUIButton
            v-else
            type="primary"
            @click="handleInvite({ userId: userInfo.userId })"
          >
            {{ t('ParticipantList.Call') }}
          </TUIButton>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { useUIKit, TUIButton, TUIToast } from '@tencentcloud/uikit-base-component-vue3';
import { useRoomState } from 'tuikit-atomicx-vue3/room';
import { RoomParticipantStatus } from 'tuikit-atomicx-vue3';
import { Avatar } from 'tuikit-atomicx-vue3';
import type { RoomParticipant } from 'tuikit-atomicx-vue3';

defineOptions({
  name: 'PendingParticipantItemH5',
});

interface Props {
  userInfo: RoomParticipant;
}

const props = defineProps<Props>();

const { currentRoom, callUserToRoom } = useRoomState();
const { t } = useUIKit();

const displayName = computed(() => props.userInfo?.userName || props.userInfo?.userId);

const isHovered = ref(false);
const showRejectedMessage = ref(false);
let rejectedTimer: ReturnType<typeof setTimeout> | null = null;

watch(
  () => props.userInfo.roomStatus,
  (newStatus) => {
    if (rejectedTimer) {
      clearTimeout(rejectedTimer);
      rejectedTimer = null;
    }

    if (newStatus === RoomParticipantStatus.CallRejected) {
      showRejectedMessage.value = true;
      rejectedTimer = setTimeout(() => {
        showRejectedMessage.value = false;
        rejectedTimer = null;
      }, 3000);
    } else {
      showRejectedMessage.value = false;
    }
  },
);

const handleMouseEnter = () => {
  isHovered.value = true;
};

const handleMouseLeave = () => {
  isHovered.value = false;
};

async function handleInvite({ userId }: { userId: string }) {
  if (!currentRoom.value?.roomId) {
    return;
  }
  try {
    await callUserToRoom({
      roomId: currentRoom.value?.roomId || '',
      userIdList: [userId],
      timeout: 60,
    });
    TUIToast.success({ message: t('ParticipantList.InviteSuccess') });
  } catch (error) {
    TUIToast.error({ message: t('ParticipantList.InviteFailed') });
    console.error('Failed to invite user to room:', error);
  }
}
</script>

<style scoped lang="scss">
.pending-participant-item-h5 {
  display: flex;
  align-items: center;
  padding: 0 20px;
  gap: 8px;
  position: relative;
  cursor: pointer;
  font-size: 14px;
  font-weight: 500;
  color: var(--text-color-secondary);
  transition: background .2s ease;
  height: 50px;
  -webkit-tap-highlight-color: transparent;

  &:active {
    background: var(--list-color-hover);
  }

  &:last-child {
    .participant-content {
      border-bottom: none;
    }
  }
}

.participant-content {
  flex: 1;
  min-width: 0;
  height: 50px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  border-bottom: 1px solid var(--stroke-color-secondary);

  .user-info {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    min-width: 0;
  }
}

.user-name {
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  min-width: 0;
}

.status-container {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-shrink: 0;
}

.status-text {
  font-size: 12px;
}
</style>
