// Web/roomkit/react/RoomKit/components/RoomParticipantList/RoomParticipantListH5.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import {
  Button,
  IconSearch,
  useUIKit,
} from '@tencentcloud/uikit-base-component-react';
import classNames from 'classnames';
import {
  DeviceStatus,
  RoomParticipantRole,
  RoomParticipantStatus,
  useRoomParticipantState,
  useRoomState,
} from 'tuikit-atomicx-react/room';
import { combineComparators, createComparator } from '../../utils/compare';
import { ParticipantActionH5 } from './ParticipantActionH5';
import { ParticipantItemH5 } from './ParticipantItemH5';
import { PendingParticipantItemH5 } from './PendingParticipantItemH5';
import { RoomActionH5 } from './RoomActionH5';
import styles from './RoomParticipantListH5.module.scss';
import type { RoomParticipant } from 'tuikit-atomicx-react/room';

type Tab = 'joined' | 'unjoined';

function makeComparator(localUserId?: string) {
  return combineComparators<RoomParticipant>(
    createComparator(p => Boolean(p.userId === localUserId)),
    createComparator(p => Boolean(p.role === RoomParticipantRole.Owner)),
    createComparator(p => Boolean(p.role === RoomParticipantRole.Admin)),
    createComparator(p => Boolean(p.screenShareStatus === DeviceStatus.On)),
    createComparator(
      p =>
        Boolean(
          p.cameraStatus === DeviceStatus.On
          && p.microphoneStatus === DeviceStatus.On,
        ),
    ),
    createComparator(p => Boolean(p.cameraStatus === DeviceStatus.On)),
    createComparator(p => Boolean(p.microphoneStatus === DeviceStatus.On)),
    createComparator(p => Boolean(p.roomStatus === RoomParticipantStatus.InCalling)),
  );
}

// Vue reference: RoomParticipantList/RoomParticipantListH5.vue (293 lines).
export function RoomParticipantListH5() {
  const { t } = useUIKit();
  const { currentRoom, callUserToRoom } = useRoomState();
  const {
    participantList,
    pendingParticipantList,
    localParticipant,
    participantListCursor,
    getParticipantList,
  } = useRoomParticipantState();

  const [searchText, setSearchText] = useState('');
  const [activeTab, setActiveTab] = useState<Tab>('joined');
  const [selectedParticipant, setSelectedParticipant]
    = useState<RoomParticipant | null>(null);
  const [actionPopupVisible, setActionPopupVisible] = useState(false);

  const roomId = currentRoom?.roomId;
  const cursorRef = useRef(participantListCursor);
  cursorRef.current = participantListCursor;
  useEffect(() => {
    if (roomId && cursorRef.current === '') {
      getParticipantList({ cursor: cursorRef.current });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [roomId]);

  const comparator = useMemo(
    () => makeComparator(localParticipant?.userId),
    [localParticipant?.userId],
  );

  const showParticipantList = useMemo(() => {
    const list
      = activeTab === 'joined' ? participantList : pendingParticipantList;
    return [...list].sort(comparator);
  }, [activeTab, participantList, pendingParticipantList, comparator]);

  const filteredParticipants = useMemo(() => {
    if (!searchText.trim()) {
      return showParticipantList;
    }
    const q = searchText.toLowerCase();
    return showParticipantList.filter(
      p =>
        (p.userName ?? '').toLowerCase().includes(q)
        || (p.nameCard ?? '').toLowerCase().includes(q)
        || (p.userId ?? '').toLowerCase().includes(q),
    );
  }, [searchText, showParticipantList]);

  // ParticipantItemH5 already no-ops when controlList is empty (Vue parity).
  const handleParticipantClick = (participant: RoomParticipant) => {
    setSelectedParticipant(participant);
    setActionPopupVisible(true);
  };

  const handleCallAllPending = async () => {
    if (!currentRoom?.roomId) {
      return;
    }
    await callUserToRoom({
      roomId: currentRoom.roomId,
      userIdList: pendingParticipantList.map(p => p.userId),
      timeout: 60,
    });
  };

  return (
    <div className={styles.participantListH5}>
      <div className={styles.searchContainer}>
        <div className={styles.searchBox}>
          <IconSearch className={styles.searchIcon} size="20" />
          <input
            className={styles.searchInput}
            type="text"
            value={searchText}
            placeholder={t('ParticipantList.Search')}
            onChange={e => setSearchText(e.target.value)}
          />
        </div>
      </div>

      <div className={styles.tabs}>
        <div
          className={classNames(styles.tab, {
            [styles.active]: activeTab === 'joined',
          })}
          onClick={() => setActiveTab('joined')}
        >
          <span className={styles.title}>
            {t('ParticipantList.Joined')}
            (
            {currentRoom?.participantCount || 0}
            )
          </span>
        </div>
        <div
          className={classNames(styles.tab, {
            [styles.active]: activeTab === 'unjoined',
          })}
          onClick={() => setActiveTab('unjoined')}
        >
          <span className={styles.title}>
            {t('ParticipantList.NotJoined')}
            (
            {pendingParticipantList.length}
            )
          </span>
        </div>
      </div>

      {activeTab === 'joined' && (
        <>
          <div className={styles.participantContainer}>
            {filteredParticipants.length === 0
              ? (
                <div className={styles.emptyState}>
                  {t('ParticipantList.NoMember')}
                </div>
              )
              : (
                filteredParticipants.map(p => (
                  <ParticipantItemH5
                    key={p.userId}
                    participant={p}
                    isLocal={p.userId === localParticipant?.userId}
                    onClick={handleParticipantClick}
                  />
                ))
              )}
          </div>
          <div className={styles.footer}>
            <RoomActionH5 />
          </div>
        </>
      )}

      {activeTab === 'unjoined' && (
        <>
          <div className={styles.unjoinedUserContainer}>
            {filteredParticipants.map(u => (
              <PendingParticipantItemH5 key={u.userId} userInfo={u} />
            ))}
          </div>
          <div className={styles.footer}>
            {pendingParticipantList.length > 0 && (
              <Button
                type="primary"
                size="big"
                style={{ minWidth: '80%' }}
                onClick={() => handleCallAllPending()}
              >
                {t('ParticipantList.CallAll')}
              </Button>
            )}
          </div>
        </>
      )}

      {actionPopupVisible && selectedParticipant && (
        <ParticipantActionH5
          visible={actionPopupVisible}
          participant={selectedParticipant}
          onVisibleChange={(visible) => {
            setActionPopupVisible(visible);
            if (!visible) {
              setSelectedParticipant(null);
            }
          }}
        />
      )}
    </div>
  );
}

// Web/roomkit/vue3/RoomKit/components/RoomParticipantList/RoomParticipantListH5.vue
<template>
  <div class="participant-list-h5">
    <div class="search-container">
      <div class="search-box">
        <IconSearch class="search-icon" size="20" />
        <input
          v-model="searchText"
          class="search-input"
          type="text"
          :placeholder="t('ParticipantList.Search')"
        >
      </div>
    </div>

    <!-- Tab navigation -->
    <div class="tabs">
      <div
        :class="['tab', { active: activeTab === 'joined' }]"
        @click="activeTab = 'joined'"
      >
        <span class="title">{{ t('ParticipantList.Joined') }}({{ currentRoom?.participantCount || 0 }})</span>
      </div>
      <div
        :class="['tab', { active: activeTab === 'unjoined' }]"
        @click="activeTab = 'unjoined'"
      >
        <span class="title">{{ t('ParticipantList.NotJoined') }}({{ pendingParticipantList.length }})</span>
      </div>
    </div>

    <template v-if="activeTab === 'joined'">
      <!-- Participant list -->
      <div class="participant-container">
        <div v-if="filteredParticipants.length === 0" class="empty-state">
          {{ t('ParticipantList.NoMember') }}
        </div>
        <ParticipantItemH5
          v-for="participant in filteredParticipants"
          :key="participant.userId"
          :participant="participant"
          :is-local="participant.userId === localParticipant?.userId"
          @click="handleParticipantClick(participant)"
        />
      </div>

      <!-- Footer actions -->
      <div class="footer">
        <RoomActionH5 v-if="activeTab === 'joined'" />
      </div>
    </template>

    <template v-if="activeTab === 'unjoined'">
      <div class="unjoined-user-container">
        <PendingParticipantItemH5
          v-for="userInfo in filteredParticipants"
          :key="userInfo.userId"
          :userInfo="userInfo"
        />
      </div>

      <!-- Footer actions -->
      <div class="footer">
        <TUIButton
          v-if="pendingParticipantList.length > 0"
          type="primary"
          size="big"
          :style="{ minWidth: '80%' }"
          @click="handleCallAllPendingParticipant"
        >
          {{ t('ParticipantList.CallAll') }}
        </TUIButton>
      </div>
    </template>

    <!-- Participant action popup -->
    <ParticipantActionH5
      :visible="showParticipantActionPopup"
      :participant="selectedParticipant"
      @update:visible="showParticipantActionPopup = $event"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, toRef } from 'vue';
import { IconSearch, useUIKit, TUIButton } from '@tencentcloud/uikit-base-component-vue3';
import { useRoomParticipantState, useRoomState, RoomParticipantStatus, RoomParticipantRole, DeviceStatus } from 'tuikit-atomicx-vue3/room';
import { combineComparators, createComparator } from '../../utils/compare';
import ParticipantActionH5 from './ParticipantActionH5.vue';
import ParticipantItemH5 from './ParticipantItemH5.vue';
import PendingParticipantItemH5 from './PendingParticipantItemH5.vue';
import RoomActionH5 from './RoomActionH5.vue';
import { useParticipantAction } from './useParticpantAction';
import type { RoomParticipant } from 'tuikit-atomicx-vue3/room';

const { pendingParticipantList } = useRoomParticipantState();

const { t } = useUIKit();
const {
  currentRoom,
  callUserToRoom,
} = useRoomState();
const {
  participantList,
  localParticipant,
  participantListCursor,
  getParticipantList,
} = useRoomParticipantState();

watch(() => currentRoom.value?.roomId, (newVal, oldVal) => {
  if (newVal && newVal !== oldVal && participantListCursor.value === '') {
    getParticipantList({ cursor: participantListCursor.value });
  }
}, { immediate: true });

const searchText = ref('');
const activeTab = ref<'joined' | 'unjoined'>('joined');
const showParticipantActionPopup = ref(false);
const selectedParticipant = ref<RoomParticipant | null>(null);

const defaultUserListCompareFunction = combineComparators(
  createComparator((userInfo: RoomParticipant) =>
    Boolean(userInfo.userId === localParticipant.value?.userId),
  ),
  createComparator((userInfo: RoomParticipant) =>
    Boolean(userInfo.role === RoomParticipantRole.Owner),
  ),
  createComparator((userInfo: RoomParticipant) =>
    Boolean(userInfo.role === RoomParticipantRole.Admin),
  ),
  createComparator((userInfo: RoomParticipant) => Boolean(userInfo.screenShareStatus === DeviceStatus.On)),
  createComparator((userInfo: RoomParticipant) =>
    Boolean(userInfo.cameraStatus === DeviceStatus.On && userInfo.microphoneStatus === DeviceStatus.On),
  ),
  createComparator((userInfo: RoomParticipant) => Boolean(userInfo.cameraStatus === DeviceStatus.On)),
  createComparator((userInfo: RoomParticipant) => Boolean(userInfo.microphoneStatus === DeviceStatus.On)),
  createComparator((userInfo: RoomParticipant) => Boolean(userInfo.roomStatus === RoomParticipantStatus.InCalling)),
);

const showParticipantList = computed(() => {
  if (activeTab.value === 'joined') {
    return [...participantList.value].sort(defaultUserListCompareFunction);
  }
  if (activeTab.value === 'unjoined') {
    return [...pendingParticipantList.value].sort(defaultUserListCompareFunction);
  }
  return [];
});

const filteredParticipants = computed(() => {
  if (!searchText.value.trim()) {
    return showParticipantList.value;
  }

  const searchLower = searchText.value.toLowerCase();
  return showParticipantList.value.filter(participant =>
    participant.userName.toLowerCase().includes(searchLower)
    || participant.nameCard.toLowerCase().includes(searchLower)
    || participant.userId.toLowerCase().includes(searchLower),
  );
});

const handleParticipantClick = (participant: RoomParticipant) => {
  const { controlList } = useParticipantAction({ targetParticipant: toRef(participant) });

  if (controlList.value.length === 0) {
    return;
  }

  selectedParticipant.value = participant;
  showParticipantActionPopup.value = true;
};

async function handleCallAllPendingParticipant() {
  const userIdList = pendingParticipantList.value.map(participant => participant.userId);
  if (!currentRoom.value?.roomId) {
    return;
  }
  await callUserToRoom({
    roomId: currentRoom.value?.roomId || '',
    userIdList,
    timeout: 60,
  });
}
</script>

<style scoped lang="scss">
.participant-list-h5 {
  width: 100%;
  height: 100%;
  background: var(--bg-color-operate);
  min-width: 200px;
  display: flex;
  flex-direction: column;
  -webkit-tap-highlight-color: transparent;
}

.search-container {
  padding: 16px 20px;
  display: flex;
  gap: 12px;
  align-items: center;

  .search-box {
    display: flex;
    align-items: center;
    flex: 1;
    height: 32px;
    padding: 0 16px;
    color: var(--text-color-primary);
    background-color: var(--bg-color-input);
    border-radius: 16px;

    .search-input {
      width: 100%;
      margin-left: 8px;
      font-size: 14px;
      color: var(--text-color-primary);
      background: none;
      border: none;
      outline: none;
    }
  }
}

.tabs {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: space-between;
  box-sizing: border-box;
  height: 36px;
  padding: 3px 4px;
  margin: 0 20px;
  cursor: pointer;
  background-color: var(--bg-color-input);
  border-radius: 20px;

  .tab {
    display: flex;
    flex: 1;
    align-items: center;
    justify-content: center;
    height: 100%;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    border-radius: 20px;

    &.active {
      background-color: var(--bg-color-operate);
    }

    .title {
      font-size: 14px;
      font-weight: 400;
      color: var(--text-color-primary);
      filter: drop-shadow(0 2px 4px var(--uikit-color-black-8))
        drop-shadow(0 6px 10px var(--uikit-color-black-8))
        drop-shadow(0 3px 14px var(--uikit-color-black-8));
      border-radius: 20px;
      transform: translateX(4px);
    }
  }
}

.participant-container, .unjoined-user-container {
  flex: 1 1 0;
  min-height: 0;
  max-height: 100%;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 10px 0;
}

.empty-state {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 200px;
  color: #999999;
  font-size: 14px;
}

.footer {
  display: flex;
  padding: 16px 20px;
  gap: 12px;
  justify-content: center;
}
</style>
