// Web/roomkit/vue3/RoomKit/components/JoinRoomButtonH5/index.vue
<template>
  <div class="room-button">
    <TUIButton
      class="button"
      size="large"
      type="primary"
      :icon="IconEnterRoom"
      @click="handleStartRoom"
    >
      {{ t('Button.JoinRoom') }}
    </TUIButton>
  </div>
</template>

<script setup lang="ts">
import { IconEnterRoom, TUIButton, useUIKit } from '@tencentcloud/uikit-base-component-vue3';

const { t } = useUIKit();

const emit = defineEmits(['join-room']);

const handleStartRoom = () => {
  emit('join-room');
};
</script>

<style lang="scss" scoped>
.room-button {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;

  .button {
    width: 100%;
    height: 100%;
  }
}
</style>

// Web/roomkit/react/RoomKit/components/JoinRoomButtonH5/JoinRoomButtonH5.tsx
import { Button, IconEnterRoom, useUIKit } from '@tencentcloud/uikit-base-component-react';
import classNames from 'classnames';
import styles from './JoinRoomButtonH5.module.scss';

export interface JoinRoomButtonH5Props {
  onJoinRoom?: () => void;
  className?: string;
}

export function JoinRoomButtonH5({ onJoinRoom, className }: JoinRoomButtonH5Props) {
  const { t } = useUIKit();

  return (
    <div className={classNames(styles.roomButton, className)}>
      <Button
        className={styles.button}
        size="large"
        type="primary"
        icon={<IconEnterRoom />}
        onClick={() => onJoinRoom?.()}
      >
        {t('Button.JoinRoom')}
      </Button>
    </div>
  );
}
