// Web/roomkit/vue3/RoomKit/components/RoomChat/ChatRegistrar.vue
<script setup lang="ts">
import { onUnmounted } from 'vue';
import { useUIKit } from '@tencentcloud/uikit-base-component-vue3';
import { conference } from '../../adapter/conference';
import { BuiltinWidget } from '../../adapter/type';
import { useRoomSidePanel } from '../../hooks/useRoomSidePanel';
import ChatButton from './ChatButton.vue';
import RoomChat from './index.vue';

const { t } = useUIKit();
const { activeWidgetId } = useRoomSidePanel();

const unregister = conference.registerWidget({
  id: BuiltinWidget.RoomChatWidget,
  zone: { pc: 'bottom-center' },
  component: ChatButton,
  props: () => ({
    isActive: activeWidgetId.value === BuiltinWidget.RoomChatWidget,
  }),
  panel: {
    title: () => t('Chat.Title'),
    component: RoomChat,
    keepAlive: true,
    props: () => ({
      isActive: activeWidgetId.value === BuiltinWidget.RoomChatWidget,
    }),
  },
});

onUnmounted(() => unregister());
</script>

<template>
  <!-- Registrar: registration-only, rendering handled by CustomWidgetRenderer -->
</template>

// Web/roomkit/react/RoomKit/components/RoomChat/ChatRegistrar.tsx
import { useEffect } from 'react';
import { useUIKit } from '@tencentcloud/uikit-base-component-react';
import { BuiltinWidget } from '../../adapter/type';
import { useRoomSidePanel } from '../../hooks/useRoomSidePanel';
import { RoomChat } from './RoomChat';

/**
 * Registration-only component: mounts the chat panel into the side panel store.
 * Returns null — the actual trigger button (`ChatButton`) must be placed
 * separately in a stable location so that layout changes do not unmount this
 * registrar and inadvertently close the panel via the cleanup function.
 */
export function ChatRegistrar() {
  const { t } = useUIKit();
  const { registerSidePanel } = useRoomSidePanel();

  useEffect(
    () => registerSidePanel({
      id: BuiltinWidget.RoomChatWidget,
      title: () => t('Chat.Title'),
      keepAlive: true,
      render: ({ isActive, keepAlive }) => (
        <RoomChat isActive={isActive} keepAlive={keepAlive} />
      ),
    }),
    [registerSidePanel, t],
  );

  return null;
}
