// Web/example/vite-react-ts/src/views/home.tsx
import { useNavigate } from 'react-router-dom';
import { PreConferenceView } from '@tencentcloud/roomkit-web-react';
import { RoomType } from 'tuikit-atomicx-react/room';
import { MessageBox, useUIKit } from '@tencentcloud/uikit-base-component-react';
import { useMediaPreference } from '@/hooks/useMediaPreference';
import './home.scss';

export default function Home() {
  const navigate = useNavigate();
  const { t } = useUIKit();

  const { setCameraPreference, setMicrophonePreference } = useMediaPreference();

  const handleLogout = () => {
    navigate('/login');
  };

  const handleCreateRoom = (roomId: string, roomType: RoomType) => {
    const targetRoomId = sessionStorage.getItem('manualRoomId') || roomId;
    sessionStorage.setItem(`room-${targetRoomId}-isCreate`, 'true');
    const search = new URLSearchParams({
      roomId: targetRoomId,
      roomType: String(roomType),
    }).toString();
    navigate({ pathname: '/room', search });
  };

  const handleJoinRoom = (roomId: string, roomType: RoomType) => {
    if (roomType === RoomType.Webinar) {
      MessageBox.alert({
        type: 'error',
        modal: false,
        showClose: false,
        title: t('Room.Alert'),
        content: t('Room.NotSupportWebinar'),
      });
      return;
    }
    sessionStorage.setItem(`room-${roomId}-isCreate`, 'false');
    const search = new URLSearchParams({
      roomId,
      roomType: String(roomType),
    }).toString();
    navigate({ pathname: '/room', search });
  };

  const handleCameraPreferenceChange = (isOpen: boolean) => {
    setCameraPreference(isOpen);
  };

  const handleMicrophonePreferenceChange = (isOpen: boolean) => {
    setMicrophonePreference(isOpen);
  };

  return (
    <div className="home-view">
      <PreConferenceView
        onLogout={handleLogout}
        onCreateRoom={handleCreateRoom}
        onJoinRoom={handleJoinRoom}
        onCameraPreferenceChange={handleCameraPreferenceChange}
        onMicrophonePreferenceChange={handleMicrophonePreferenceChange}
      />
    </div>
  );
}

// Web/example/vite-vue3-ts/src/views/home.vue
<template>
  <div class="home-view">
    <PreConferenceView
      @logout="handleLogout"
      @create-room="handleCreateRoom"
      @join-room="handleJoinRoom"
      @camera-preference-change="handleCameraPreferenceChange"
      @microphone-preference-change="handleMicrophonePreferenceChange"
    />
  </div>
</template>

<script setup lang="ts">
import { PreConferenceView } from '@tencentcloud/roomkit-web-vue3';
import { useRouter } from 'vue-router';
import { useMediaPreference } from '../hooks/useMediaPreference';
import type { TUIRoomType } from 'tuikit-atomicx-vue3/room';

const router = useRouter();

const { setMicrophonePreference, setCameraPreference } = useMediaPreference();

const handleCameraPreferenceChange = (isOpen: boolean) => {
  setCameraPreference(isOpen);
};

const handleMicrophonePreferenceChange = (isOpen: boolean) => {
  setMicrophonePreference(isOpen);
};

const handleLogout = () => {
  router.push('/login');
};

const handleCreateRoom = async (roomId: string, roomType: TUIRoomType) => {
  const targetRoomId = sessionStorage.getItem('manualRoomId') || roomId;
  sessionStorage.setItem(`room-${targetRoomId}-isCreate`, 'true');
  router.push({
    path: '/room',
    query: { roomId: targetRoomId, roomType },
  });
};

const handleJoinRoom = async (roomId: string, roomType: TUIRoomType) => {
  sessionStorage.setItem(`room-${roomId}-isCreate`, 'false');
  router.push({
    path: '/room',
    query: { roomId, roomType },
  });
};
</script>

<style lang="scss" scoped>
.home-view {
  position: relative;
  width: 100%;
  height: 100%;
}
</style>
