// Web/example/vite-react-ts/src/views/homeH5.tsx
import { useNavigate } from 'react-router-dom';
import { PreConferenceViewH5 } from '@tencentcloud/roomkit-web-react';
import { useMediaPreference } from '@/hooks/useMediaPreference';

export default function HomeH5() {
  const navigate = useNavigate();
  const { setCameraPreference, setMicrophonePreference } = useMediaPreference();

  const handleLogout = () => {
    navigate('/login');
  };

  const handleCreateRoom = (roomId: string) => {
    const targetRoomId = sessionStorage.getItem('manualRoomId') || roomId;
    sessionStorage.setItem(`room-${targetRoomId}-isCreate`, 'true');
    const search = new URLSearchParams({ roomId: targetRoomId }).toString();
    navigate({ pathname: '/room', search });
  };

  const handleJoinRoom = (roomId: string) => {
    sessionStorage.setItem(`room-${roomId}-isCreate`, 'false');
    const search = new URLSearchParams({ roomId }).toString();
    navigate({ pathname: '/room', search });
  };

  const handleCameraPreferenceChange = (isOpen: boolean) => {
    setCameraPreference(isOpen);
  };

  const handleMicrophonePreferenceChange = (isOpen: boolean) => {
    setMicrophonePreference(isOpen);
  };

  return (
    <PreConferenceViewH5
      onLogout={handleLogout}
      onCreateRoom={handleCreateRoom}
      onJoinRoom={handleJoinRoom}
      onCameraPreferenceChange={handleCameraPreferenceChange}
      onMicrophonePreferenceChange={handleMicrophonePreferenceChange}
    />
  );
}

// Web/example/vite-vue3-ts/src/views/homeH5.vue
<template>
  <PreConferenceViewH5
    @logout="handleLogout"
    @create-room="handleCreateRoom"
    @join-room="handleJoinRoom"
    @camera-preference-change="handleCameraPreferenceChange"
    @microphone-preference-change="handleMicrophonePreferenceChange"
  />
</template>

<script setup lang="ts">
import { PreConferenceViewH5 } from '@tencentcloud/roomkit-web-vue3';
import { useRouter } from 'vue-router';
import { useMediaPreference } from '../hooks/useMediaPreference';

const { setCameraPreference, setMicrophonePreference } = useMediaPreference();

const router = useRouter();

const handleCameraPreferenceChange = (isOpen: boolean) => {
  setCameraPreference(isOpen);
};

const handleMicrophonePreferenceChange = (isOpen: boolean) => {
  setMicrophonePreference(isOpen);
};

const handleLogout = () => {
  router.push('/login');
};

const handleCreateRoom = async (roomId: string) => {
  const targetRoomId = sessionStorage.getItem('manualRoomId') || roomId;
  sessionStorage.setItem(`room-${targetRoomId}-isCreate`, 'true');
  router.push({
    path: '/room',
    query: { roomId: targetRoomId },
  });
};

const handleJoinRoom = async (roomId: string) => {
  sessionStorage.setItem(`room-${roomId}-isCreate`, 'false');
  router.push({
    path: '/room',
    query: { roomId },
  });
};
</script>

<style lang="scss" scoped></style>
