// Web/example/vite-react-ts/src/views/roomH5.tsx
import { useEffect, useRef } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useUIKit } from '@tencentcloud/uikit-base-component-react';
import {
  ConferenceMainViewH5,
  RoomEvent as ConferenceRoomEvent,
  conference,
} from '@tencentcloud/roomkit-web-react';
import {
  VideoQuality,
  useDeviceState,
  useLoginState,
  useRoomModal,
  useRoomParticipantState,
  useRoomState,
} from 'tuikit-atomicx-react/room';
import { useMediaPreference } from '@/hooks/useMediaPreference';

export default function RoomH5() {
  const { t } = useUIKit();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  const { loginUserInfo } = useLoginState();
  const { currentRoom } = useRoomState();
  const {
    localVideoQuality,
    openLocalCamera,
    updateVideoQuality,
    openLocalMicrophone,
    closeLocalMicrophone,
  } = useDeviceState();
  const { muteMicrophone, unmuteMicrophone } = useRoomParticipantState();
  const { getMicrophonePreference, getCameraPreference } = useMediaPreference();
  const { handleErrorWithModal } = useRoomModal();

  const roomId = searchParams.get('roomId') || '';
  const password = searchParams.get('password') ?? undefined;

  const loginUserInfoRef = useRef(loginUserInfo);
  loginUserInfoRef.current = loginUserInfo;
  const localVideoQualityRef = useRef(localVideoQuality);
  localVideoQualityRef.current = localVideoQuality;

  useEffect(() => {
    if (!roomId) {
      navigate('/home', { replace: true });
    }
  }, []);

  const userId = loginUserInfo?.userId;
  const hasEnteredRoomRef = useRef(false);
  useEffect(() => {
    if (!userId || !roomId || hasEnteredRoomRef.current) {
      return;
    }
    if (currentRoom?.roomId) {
      return;
    }
    hasEnteredRoomRef.current = true;

    const enterRoom = async () => {
      const isCreateKey = `room-${roomId}-isCreate`;
      const isCreate = sessionStorage.getItem(isCreateKey) === 'true';
      sessionStorage.removeItem(isCreateKey);
      try {
        if (isCreate) {
          await handleStartConference();
        } else {
          await handleJoinConference();
        }
      } catch (error) {
        handleErrorWithModal(error as { code?: number; message?: string });
        navigate('/home', { replace: true });
      }
    };

    const handleStartConference = async () => {
      await handleOpenMicrophone();
      try {
        const ownerName =
          loginUserInfoRef.current?.userName ||
          loginUserInfoRef.current?.userId ||
          '';
        await conference.createAndJoinRoom({
          roomId,
          options: {
            roomName: `${ownerName}${t('Room.TemporaryMeeting')}`,
          },
        });
      } catch (error) {
        await closeLocalMicrophone();
        throw error;
      }
    };

    const handleJoinConference = async () => {
      await handleOpenMicrophone();
      try {
        await conference.joinRoom({ roomId, password });
      } catch (error) {
        await closeLocalMicrophone();
        throw error;
      }
    };

    const handleOpenMicrophone = async () => {
      try {
        await muteMicrophone();
        await openLocalMicrophone();
      } catch (error) {
        handleErrorWithModal(error as { code?: number; message?: string });
      }
      if (getMicrophonePreference()) {
        await unmuteMicrophone();
      }
    };

    void enterRoom();
  }, [userId]);

  const currentRoomId = currentRoom?.roomId;
  const prevRoomIdRef = useRef<string | undefined>(undefined);
  useEffect(() => {
    const prevRoomId = prevRoomIdRef.current;
    prevRoomIdRef.current = currentRoomId;
    if (prevRoomId || !currentRoomId) {
      return;
    }
    const openCamera = async () => {
      if (!localVideoQualityRef.current) {
        updateVideoQuality({ quality: VideoQuality.Quality720P });
      }
      if (getCameraPreference()) {
        try {
          await openLocalCamera();
        } catch (error) {
          handleErrorWithModal(error as { code?: number; message?: string });
        }
      }
    };
    void openCamera();
  }, [currentRoomId]);

  useEffect(() => {
    const handleBackHome = () => {
      navigate('/home', { replace: true });
    };
    conference.on(ConferenceRoomEvent.ROOM_DISMISS, handleBackHome);
    conference.on(ConferenceRoomEvent.ROOM_LEAVE, handleBackHome);
    conference.on(ConferenceRoomEvent.ROOM_ERROR, handleBackHome);
    conference.on(ConferenceRoomEvent.KICKED_OUT, handleBackHome);
    return () => {
      conference.off(ConferenceRoomEvent.ROOM_DISMISS, handleBackHome);
      conference.off(ConferenceRoomEvent.ROOM_LEAVE, handleBackHome);
      conference.off(ConferenceRoomEvent.ROOM_ERROR, handleBackHome);
      conference.off(ConferenceRoomEvent.KICKED_OUT, handleBackHome);
    };
  }, []);

  return <ConferenceMainViewH5 />;
}

// Web/example/vite-vue3-ts/src/views/roomH5.vue
<template>
  <ConferenceMainViewH5 />
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, watch } from 'vue';
import { conference, ConferenceMainViewH5, RoomEvent as ConferenceRoomEvent, BuiltinWidget } from '@tencentcloud/roomkit-web-vue3';
import {
  useUIKit,
} from '@tencentcloud/uikit-base-component-vue3';
import {
  useLoginState,
  useRoomState,
  useDeviceState,
  VideoQuality,
  useRoomParticipantState,
  useRoomModal,
} from 'tuikit-atomicx-vue3/room';
import { useRoute, useRouter } from 'vue-router';
import { useMediaPreference } from '../hooks/useMediaPreference';

const route = useRoute();
const router = useRouter();
const { t } = useUIKit();
const { handleErrorWithModal } = useRoomModal();

const { loginUserInfo } = useLoginState();
const { currentRoom } = useRoomState();
const { localVideoQuality, openLocalCamera, updateVideoQuality, openLocalMicrophone, closeLocalMicrophone } = useDeviceState();
const { muteMicrophone, unmuteMicrophone } = useRoomParticipantState();
const { getMicrophonePreference, getCameraPreference } = useMediaPreference();

const { roomId, password } = route.query as { roomId: string; password?: string };

if (!roomId) {
  router.replace('/home');
}

watch(() => loginUserInfo.value?.userId, async (userId) => {
  if (!userId || !roomId || currentRoom.value?.roomId) {
    return;
  }
  await handleEnterRoom();
}, { immediate: true });

watch(() => currentRoom.value?.roomId, async (currentRoomId, prevRoomId) => {
  if (!prevRoomId && currentRoomId) {
    handleOpenCamera();
  }
}, { immediate: true });

async function handleEnterRoom() {
  const isCreateKey = `room-${roomId}-isCreate`;
  const isCreate = sessionStorage.getItem(isCreateKey) === 'true';
  sessionStorage.removeItem(isCreateKey);
  try {
    if (isCreate) {
      await handleStartConference();
    } else {
      await handleJoinConference();
    }
  } catch (error) {
    handleErrorWithModal(error);
    router.replace('/home');
  }
}

async function handleStartConference() {
  await handleOpenMicrophone();
  try {
    await conference.createAndJoinRoom({
      roomId,
      options: {
        roomName: `${loginUserInfo.value?.userName || loginUserInfo.value?.userId}${t('Room.TemporaryMeeting')}`,
      },
    });
  } catch (error: unknown) {
    await closeLocalMicrophone();
  }
}

async function handleJoinConference() {
  await handleOpenMicrophone();
  try {
    await conference.joinRoom({
      roomId,
      password,
    });
  } catch (error: unknown) {
    await closeLocalMicrophone();
  }
}

async function handleOpenCamera() {
  if (!localVideoQuality.value) {
    updateVideoQuality({ quality: VideoQuality.Quality720P });
  }
  if (getCameraPreference()) {
    try {
      await openLocalCamera();
    } catch (error) {
      handleErrorWithModal(error);
    }
  }
}

async function handleOpenMicrophone() {
  try {
    await muteMicrophone();
    await openLocalMicrophone();
  } catch (error) {
    handleErrorWithModal(error);
  }
  if (getMicrophonePreference()) {
    await unmuteMicrophone();
  }
}

const handleBackHome = () => {
  router.replace('/home');
};

onMounted(() => {
  conference.on(ConferenceRoomEvent.ROOM_DISMISS, handleBackHome);
  conference.on(ConferenceRoomEvent.ROOM_LEAVE, handleBackHome);
  conference.on(ConferenceRoomEvent.ROOM_ERROR, handleBackHome);
  conference.on(ConferenceRoomEvent.KICKED_OUT, handleBackHome);
});

onUnmounted(() => {
  conference.off(ConferenceRoomEvent.ROOM_DISMISS, handleBackHome);
  conference.off(ConferenceRoomEvent.ROOM_LEAVE, handleBackHome);
  conference.off(ConferenceRoomEvent.ROOM_ERROR, handleBackHome);
  conference.off(ConferenceRoomEvent.KICKED_OUT, handleBackHome);
});

</script>

<style lang="scss" scoped>

</style>
