// Web/roomkit/react/RoomKit/components/CloudRecording/CloudRecordingButton.tsx
import { IconRecording, IconStartRecord, useUIKit } from '@tencentcloud/uikit-base-component-react';
import { IconButton } from '../base/IconButton';
import { useCloudRecordingAction } from './useCloudRecordingAction';

export function CloudRecordingButton() {
  const { t } = useUIKit();
  const { isRecording, handleRecordingClick } = useCloudRecordingAction();

  return (
    <IconButton
      title={isRecording ? t('CloudRecording.RecordingLabel') : t('CloudRecording.RecordLabel')}
      onClickIcon={handleRecordingClick}
    >
      {isRecording ? <IconRecording size="24" /> : <IconStartRecord size="24" />}
    </IconButton>
  );
}

// Web/roomkit/vue3/RoomKit/components/CloudRecording/CloudRecordingButton.vue
<template>
  <icon-button
    :title="isRecording ? t('CloudRecording.RecordingLabel') : t('CloudRecording.RecordLabel')"
    :is-active="isRecording"
    @click-icon="handleRecordingClick"
  >
    <IconRecording v-if="isRecording" size="24" />
    <IconStartRecord v-else size="24" />
  </icon-button>
</template>

<script setup lang="ts">
import { IconRecording, IconStartRecord, useUIKit } from '@tencentcloud/uikit-base-component-vue3';
import IconButton from '../base/IconButton.vue';
import { useCloudRecordingAction } from './useCloudRecordingAction';

const { t } = useUIKit();
const { isRecording, handleRecordingClick } = useCloudRecordingAction();
</script>
