// Web/roomkit/react/RoomKit/views/ConferenceMainView/ConferenceMainView.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { IconLoadingSchedule, Watermark, useUIKit } from '@tencentcloud/uikit-base-component-react';
import classNames from 'classnames';
import {
  KickedOutOfRoomReason,
  RoomEvent,
  RoomLayoutTemplate,
  RoomParticipantEvent,
  RoomParticipantRole,
  RoomType,
  useLoginState,
  useRoomParticipantState,
  useRoomState,
} from 'tuikit-atomicx-react/room';
import { conference as conferenceImpl, useFeatureConfig } from '../../adapter/conference';
import {
  RoomEvent as ConferenceRoomEvent,
} from '../../adapter/type';
import {
  CameraButton,
  ChatRegistrar,
  CurrentRoomInfo,
  InviteButton,
  LanguageButton,
  LayoutButton,
  LeaveRoomButton,
  LocalNetworkInfo,
  LoginUserInfo,
  MemberRegistrar,
  MicButton,
  PasswordDialog,
  RoomLayoutView,
  RoomSidePanel,
  ScreenShareButton,
  SettingsButton,
  ThemeButton,
} from '../../components';
import { OverflowBar } from '../../components/OverflowBar';
import { useCustomizedAutoPlayDialog } from '../../hooks/useCustomizedAutoPlayDialog';
import { useLoadingFade } from '../../hooks/useLoadingFade';
import useRoomLifeCycle from '../../hooks/useRoomLifeCycle';
import { useRoomSidePanel } from '../../hooks/useRoomSidePanel';
import { useRoomTips } from '../../hooks/useRoomTips';
import { useRoomToolbar } from '../../hooks/useRoomToolbar';
import { eventCenter } from '../../utils/eventCenter';
import styles from './ConferenceMainView.module.scss';
import type { IConference } from '../../adapter/type';
import type { ParticipantViewSlotProps } from '../../components';

type CachedRoomInfo = NonNullable<ReturnType<typeof useRoomState>['currentRoom']>;

const conference = conferenceImpl as unknown as IConference;

export interface ConferenceMainViewProps {
  /**
   * Custom renderer for each participant tile, forwarded to the underlying
   * `RoomLayoutView`. When omitted the layout falls back to its default tile.
   */
  renderParticipantView?: (props: ParticipantViewSlotProps) => ReactNode;
}

export function ConferenceMainView(props: ConferenceMainViewProps) {
  const { renderParticipantView } = props;

  const { t } = useUIKit();
  const roomPageRef = useRef<HTMLDivElement | null>(null);
  const { showToolbar } = useRoomToolbar(roomPageRef);
  const {
    activeId,
    sidePanelTitle,
    sidePanels,
    closePanel,
  } = useRoomSidePanel();

  useCustomizedAutoPlayDialog();
  useRoomTips();

  const { loginUserInfo } = useLoginState();
  const {
    currentRoom,
    subscribeEvent: subscribeRoomEvent,
    unsubscribeEvent: unsubscribeRoomEvent,
  } = useRoomState();
  const {
    localParticipant,
    participantList,
    audienceListCursor,
    participantListCursor,
    getParticipantList,
    subscribeEvent: subscribeRoomParticipantEvent,
    unsubscribeEvent: unsubscribeRoomParticipantEvent,
  } = useRoomParticipantState();
  const {
    isJoiningRoom,
    joiningRoomId,
    roomPasswordVisible,
    setRoomPasswordVisible,
    handleJoinRoomError,
  } = useRoomLifeCycle();
  const { mounted: loadingMounted, active: loadingActive } = useLoadingFade(isJoiningRoom);

  // Role / room-type derivations mirror the Vue `computed()` block 1:1.
  const isWebinar = currentRoom?.roomType === RoomType.Webinar;
  const isOwner = localParticipant?.role === RoomParticipantRole.Owner;
  const isParticipant = participantList.some(
    participant => participant.userId === localParticipant?.userId,
  );
  const notWebinar = !isWebinar;
  const ownerOrNotWebinar = !isWebinar || isOwner;

  const [participantViewLayout, setParticipantViewLayout] = useState<
    RoomLayoutTemplate | undefined
  >(undefined);
  const handleLayoutUpdate = (layout: RoomLayoutTemplate) => {
    setParticipantViewLayout(layout);
  };

  const cachedRoomInfoRef = useRef<CachedRoomInfo | null>(null);
  useEffect(() => {
    if (currentRoom?.roomId) {
      cachedRoomInfoRef.current = { ...currentRoom };
    }
  }, [currentRoom]);

  const handlePasswordCancel = () => {
    eventCenter.emit(ConferenceRoomEvent.ROOM_ERROR);
  };
  const handleLeaveRoom = () => {
    eventCenter.emit(ConferenceRoomEvent.ROOM_LEAVE, {
      roomInfo: cachedRoomInfoRef.current || currentRoom,
    });
  };
  const handleEndRoom = () => {
    eventCenter.emit(ConferenceRoomEvent.ROOM_DISMISS, {
      roomInfo: cachedRoomInfoRef.current || currentRoom,
    });
  };

  const watermarkConfig = useMemo(() => conference.getFeatureConfig('watermark'), []);
  const watermarkEnabled = watermarkConfig?.enable !== false;
  const watermarkContent = useMemo(
    () =>
      watermarkConfig?.content ?? [
        loginUserInfo?.userName || '',
        loginUserInfo?.userId || '',
      ],
    [watermarkConfig, loginUserInfo?.userName, loginUserInfo?.userId],
  );
  const watermarkFont = useMemo(
    () => watermarkConfig?.font ?? { fontSize: 16 },
    [watermarkConfig],
  );

  const layoutTemplateConfig = useFeatureConfig('layoutTemplate');
  useEffect(() => {
    if (currentRoom?.roomType === RoomType.Webinar) {
      setParticipantViewLayout(undefined);
      return;
    }
    setParticipantViewLayout(layoutTemplateConfig ?? RoomLayoutTemplate.GridLayout);
  }, [currentRoom?.roomType, layoutTemplateConfig]);

  const participantListCursorRef = useRef(participantListCursor);
  participantListCursorRef.current = participantListCursor;
  const audienceListCursorRef = useRef(audienceListCursor);
  audienceListCursorRef.current = audienceListCursor;
  const prevRoomIdRef = useRef<string | undefined>(undefined);
  useEffect(() => {
    const roomId = currentRoom?.roomId;
    const oldRoomId = prevRoomIdRef.current;
    prevRoomIdRef.current = roomId;
    if (!oldRoomId && roomId) {
      const fetchLists = async () => {
        await getParticipantList({ cursor: participantListCursorRef.current });
      };
      fetchLists();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentRoom?.roomId]);

  useEffect(() => {
    const onRoomEnded = () => {
      eventCenter.emit(ConferenceRoomEvent.ROOM_DISMISS, {
        roomInfo: cachedRoomInfoRef.current || currentRoom,
      });
    };

    const onKickedFromRoom = (eventInfo: {
      reason: KickedOutOfRoomReason;
      message: string;
    }) => {
      eventCenter.emit(ConferenceRoomEvent.KICKED_OUT, eventInfo);
    };

    subscribeRoomEvent(RoomEvent.onRoomEnded, onRoomEnded);
    subscribeRoomParticipantEvent(
      RoomParticipantEvent.onKickedFromRoom,
      onKickedFromRoom,
    );

    return () => {
      unsubscribeRoomEvent(RoomEvent.onRoomEnded, onRoomEnded);
      unsubscribeRoomParticipantEvent(
        RoomParticipantEvent.onKickedFromRoom,
        onKickedFromRoom,
      );
      closePanel();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const layoutView = (
    <RoomLayoutView
      layoutTemplate={participantViewLayout}
      onLayoutTemplateChange={handleLayoutUpdate}
      renderParticipantView={renderParticipantView}
    />
  );

  return (
    <div
      id="roomPage"
      ref={roomPageRef}
      className={styles.roomPage}
    >
      {loadingMounted && (
        <div
          className={classNames(styles.loadingMask, {
            [styles.loadingMaskActive]: loadingActive,
          })}
        >
          <div className={styles.loadingSpinner}>
            <IconLoadingSchedule className={styles.loadingCircular} size="42px" />
            <p className={styles.loadingText}>{t('Room.EnteringRoom')}</p>
          </div>
        </div>
      )}

      <div className={styles.roomContainer}>
        <header
          className={classNames(styles.header, {
            [styles.toolbarHidden]: !showToolbar,
          })}
        >
          <div className={styles.headerLeft}>
            <ThemeButton />
            {notWebinar && (
              <LayoutButton
                layout={participantViewLayout}
                onLayoutChange={handleLayoutUpdate}
              />
            )}
            <LocalNetworkInfo />
          </div>
          <div className={styles.headerCenter}>
            <CurrentRoomInfo />
          </div>
          <div className={styles.headerRight}>
            <LanguageButton />
            <LoginUserInfo showLogout={false} />
          </div>
        </header>

        <main className={styles.roomMain}>
          {watermarkEnabled
            ? (
              <Watermark font={watermarkFont} content={watermarkContent}>
                {layoutView}
              </Watermark>
            )
            : (
              layoutView
            )}
        </main>

        <footer
          className={classNames(styles.controlBar, {
            [styles.toolbarHidden]: !showToolbar,
          })}
        >
          <div className={styles.controlLeft}>
            {(!isWebinar || isParticipant || isOwner) && <MicButton />}
            {ownerOrNotWebinar && <CameraButton />}
          </div>

          <OverflowBar className={styles.controlCenter}>
            {ownerOrNotWebinar && <ScreenShareButton />}
            {notWebinar && <InviteButton />}
            {notWebinar && <ChatRegistrar />}
            <MemberRegistrar />
            {ownerOrNotWebinar && <SettingsButton />}
          </OverflowBar>

          <div className={styles.controlRight}>
            <LeaveRoomButton onLeave={handleLeaveRoom} onEnd={handleEndRoom} />
          </div>
        </footer>

        <PasswordDialog
          visible={roomPasswordVisible}
          onVisibleChange={setRoomPasswordVisible}
          roomId={joiningRoomId}
          onCancel={handlePasswordCancel}
          onError={handleJoinRoomError}
        />
      </div>

      <RoomSidePanel
        className={classNames(styles.sidePanel, {
          [styles.sidePanelVisible]: activeId,
        })}
        title={sidePanelTitle}
        onClose={closePanel}
        activeId={activeId}
        panels={sidePanels}
      />
    </div>
  );
}

// Web/roomkit/vue3/RoomKit/views/ConferenceMainView/index.vue
<template>
  <div
    id="roomPage"
    ref="roomPageRef"
    v-tui-loading="{
      visible: isJoiningRoom,
      text: t('Room.EnteringRoom'),
      background: 'var(--bg-color-topbar)',
    }"
    class="room-page"
  >
    <div class="room-container" :class="{ 'has-side-panel': activeTab }">
      <header v-show="showToolbar" class="header">
        <div class="header-left">
          <ThemeButton />
          <LayoutButton
            v-if="!isWebinar"
            :layout="participantViewLayout"
            @update:layout="handleLayoutUpdate"
          />
          <LocalNetworkInfo />
        </div>
        <div class="header-center">
          <CurrentRoomInfo />
        </div>
        <div class="header-right">
          <LanguageButton />
          <LoginUserInfo :show-logout="false" />
        </div>
      </header>

      <main

        class="room-main"
      >
        <TUIWatermark
          :font="{ fontSize: 16 }"
          :content="[
            loginUserInfo?.userName || '',
            loginUserInfo?.userId || '',
          ]"
        >
          <RoomLayoutView
            :layout-template="participantViewLayout"
            @update:layout-template="handleLayoutUpdate"
          />
        </TUIWatermark>
      </main>

      <footer v-show="showToolbar" class="control-bar">
        <div v-if="isWebinar" class="control-left">
          <MicButton v-if="isGuest || isOwner" />
          <CameraButton v-if="isOwner" />
          <RaiseHandsButton v-if="isAudience" />
        </div>
        <div v-else class="control-left">
          <MicButton />
          <CameraButton />
        </div>

        <div class="control-center">
          <ScreenShareButton v-if="!isWebinar || isOwner" />
          <CallButton v-if="!isWebinar" />
          <BarrageButton
            v-if="isWebinar"
            :is-chat-open="activeTab === RoomTabKey.Barrage"
            @click="toggleSidePanel(RoomTabKey.Barrage)"
          />
          <RaiseHandsList v-if="isWebinar && isOwner" />
          <ChatButton
            v-if="!isWebinar"
            :is-chat-open="activeTab === RoomTabKey.Chat"
            @click="toggleSidePanel(RoomTabKey.Chat)"
          />
          <ParticipantButton
            @click="toggleSidePanel(RoomTabKey.ParticipantList)"
          />
          <MoreButton v-if="!isWebinar || isOwner">
            <VirtualBackgroundButton v-if="!isWebinar" />
            <BasicBeautyButton v-if="!isWebinar || isOwner" />
            <AIToolsButton v-if="!isWebinar && AIToolsButtonConfig?.visible" />
            <SettingButton v-if="!isWebinar || isOwner" />
          </MoreButton>
        </div>

        <div class="control-right">
          <LeaveRoomButton @leave="handleLeaveRoom" @end="handleEndRoom" />
        </div>
      </footer>
      <PasswordDialog
        v-model="roomPasswordVisible"
        :room-id="joiningRoomId"
        @cancel="handlePasswordCancel"
        @error="handleJoinRoomError"
      />
    </div>
    <RoomSidePanel
      class="side-panel"
      :class="{ 'side-panel-visible': activeTab }"
      :title="sidePanelTitle"
      @close="closePanel"
    >
      <RoomParticipantList v-if="activeTab === RoomTabKey.ParticipantList" />
      <RoomChat
        v-show="activeTab === RoomTabKey.Chat"
        v-if="!isWebinar"
        :is-chat-open="activeTab === RoomTabKey.Chat"
      />
      <RoomBarrage v-show="isWebinar && activeTab === RoomTabKey.Barrage" :is-chat-open="activeTab === RoomTabKey.Barrage" />
      <RealtimeMessageList
        v-if="activeTab === RoomTabKey.AIToolsRealtimeMessageList"
      />
    </RoomSidePanel>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted, computed } from 'vue';
import type { Ref } from 'vue';
import {
  useUIKit,
  TUIWatermark,
  vTuiLoading,
} from '@tencentcloud/uikit-base-component-vue3';
import {
  RoomParticipantList,
  useLoginState,
  useRoomState,
  useRoomParticipantState,
  RoomLayoutTemplate,
  RealtimeMessageList,
  RoomEvent,
  RoomParticipantEvent,
  KickedOutOfRoomReason,
  RoomType,
  RoomParticipantRole,
  useAITranscriberState,
} from 'tuikit-atomicx-vue3/room';
import { conference } from '../../adapter/conference';
import { ComponentName, RoomEvent as ConferenceRoomEvent } from '../../adapter/type';
import {
  ThemeButton,
  LanguageButton,
  LayoutButton,
  LocalNetworkInfo,
  CurrentRoomInfo,
  LoginUserInfo,
  RoomLayoutView,
  ScreenShareButton,
  SettingButton,
  CameraButton,
  MicButton,
  MoreButton,
  ParticipantButton,
  CallButton,
  RoomChat,
  VirtualBackgroundButton,
  BasicBeautyButton,
  PasswordDialog,
  LeaveRoomButton,
  ChatButton,
  RoomSidePanel,
  BarrageButton,
  RaiseHandsButton,
  RaiseHandsList,
  AIToolsButton,
} from '../../components';
import RoomBarrage from '../../components/RoomBarrage/RoomBarrage.vue';
import useCustomizedAutoPlayDialog from '../../hooks/useCustomizedAutoPlayDialog';
import useRoomLifeCycle from '../../hooks/useRoomLifeCycle';
import { useRoomSidePanel, RoomTabKey } from '../../hooks/useRoomSidePanel';
import { useRoomTips } from '../../hooks/useRoomTips';
import { useRoomToolbar } from '../../hooks/useRoomToolbar';
import { eventCenter } from '../../utils/eventCenter';

const AIToolsButtonConfig = conference.getComponentConfig(ComponentName.AIToolsButton);

const { t } = useUIKit();
const roomPageRef = ref<HTMLElement | null>(null);
const { showToolbar } = useRoomToolbar(roomPageRef);
const { activeTab, sidePanelTitle, toggleSidePanel, closePanel } = useRoomSidePanel();

useCustomizedAutoPlayDialog();
useRoomTips();

const { loginUserInfo } = useLoginState();
const {
  currentRoom,
  subscribeEvent: subscribeRoomEvent,
  unsubscribeEvent: unsubscribeRoomEvent,
} = useRoomState();
const {
  localParticipant,
  participantList,
  audienceListCursor,
  participantListCursor,
  getParticipantList,
  getAudienceList,
  subscribeEvent: subscribeRoomParticipantEvent,
  unsubscribeEvent: unsubscribeRoomParticipantEvent,
} = useRoomParticipantState();
const { startRealtimeTranscriber } = useAITranscriberState();

const {
  isJoiningRoom,
  joiningRoomId,
  roomPasswordVisible,
  handleJoinRoomError,
} = useRoomLifeCycle();

const isWebinar = computed(() => currentRoom.value?.roomType === RoomType.Webinar);
const isOwner = computed(() => localParticipant.value?.role === RoomParticipantRole.Owner);
const isGuest = computed(() => participantList.value.some(participant => participant.userId === localParticipant.value?.userId));
const isAudience = computed(() => !participantList.value.some(participant => participant.userId === localParticipant.value?.userId));
const participantViewLayout: Ref<RoomLayoutTemplate | undefined> = ref(undefined);
function handleLayoutUpdate(layout: RoomLayoutTemplate) {
  participantViewLayout.value = layout;
}

watch(() => currentRoom.value?.roomType, (newRoomType) => {
  if (newRoomType === RoomType.Webinar) {
    participantViewLayout.value = undefined;
  } else {
    participantViewLayout.value = RoomLayoutTemplate.GridLayout;
  }
}, { immediate: true });

watch(
  () => currentRoom.value?.roomId,
  async (roomId, oldRoomId) => {
    if (!oldRoomId && roomId) {
      await getParticipantList({ cursor: participantListCursor.value });
      await getAudienceList({ cursor: audienceListCursor.value });
      if (isOwner.value && AIToolsButtonConfig?.visible) {
        await startRealtimeTranscriber({
          sourceLanguage: 'zh',
          translationLanguages: ['en'],
        });
      }
    }
  },
  { immediate: true },
);

const handlePasswordCancel = () => {
  eventCenter.emit(ConferenceRoomEvent.ROOM_ERROR);
};
const handleLeaveRoom = () => {
  eventCenter.emit(ConferenceRoomEvent.ROOM_LEAVE);
};
const handleEndRoom = () => {
  eventCenter.emit(ConferenceRoomEvent.ROOM_DISMISS);
};
const onRoomEnded = () => {
  eventCenter.emit(ConferenceRoomEvent.ROOM_DISMISS, {});
};

const onKickedFromRoom = (eventInfo: {
  reason: KickedOutOfRoomReason;
  message: string;
}) => {
  eventCenter.emit(ConferenceRoomEvent.KICKED_OUT, eventInfo);
};

onMounted(() => {
  subscribeRoomEvent(RoomEvent.onRoomEnded, onRoomEnded);
  subscribeRoomParticipantEvent(
    RoomParticipantEvent.onKickedFromRoom,
    onKickedFromRoom,
  );
});

onUnmounted(() => {
  unsubscribeRoomEvent(RoomEvent.onRoomEnded, onRoomEnded);
  unsubscribeRoomParticipantEvent(
    RoomParticipantEvent.onKickedFromRoom,
    onKickedFromRoom,
  );
  closePanel();
});
</script>

<style lang="scss" scoped>
.room-page {
  position: relative;
  display: flex;
  flex-direction: row;
  width: 100vw;
  min-width: 1150px;
  height: 100vh;
  overflow: hidden;
  font-family:
    -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.room-container {
  position: relative;
  display: flex;
  flex-direction: column;
  width: 100%;
  transition: width 0.3s cubic-bezier(0.4, 0, 0.2, 1);

  &.has-side-panel {
    width: calc(100% - 400px);
  }
}

.header {
  position: absolute;
  top: 0;
  left: 0;
  z-index: 1;
  box-sizing: border-box;
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  height: 56px;
  padding: 16px 20px;
  background-color: var(--bg-color-operate);
  border-bottom: 1px solid var(--stroke-color-primary);
  box-shadow: 0 1px 0 var(--uikit-color-black-8);

  &-left {
    display: flex;
    flex: 1;
    gap: 24px;
    justify-content: flex-start;
  }

  &-center {
    flex: 1;
    height: 100%;
    text-align: center;
  }

  &-right {
    display: flex;
    flex: 1;
    gap: 16px;
    align-items: center;
    justify-content: flex-end;
  }
}

.room-main {
  position: absolute;
  right: 0;
  left: 0;
  display: flex;
  width: 100%;
  height: 100%;
  min-height: 0;
  background-color: var(--bg-color-topbar);
}

.control-bar {
  position: absolute;
  bottom: 0;
  left: 0;
  z-index: 1;
  box-sizing: border-box;
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  height: 72px;
  padding: 0 10px;
  background: var(--bg-color-operate);
  border-top: 1px solid var(--stroke-color-primary);

  .control-left {
    display: flex;
    flex: 1;
    gap: 16px;
    align-items: center;
    justify-content: flex-start;
  }

  .control-center {
    display: flex;
    gap: 16px;
    align-items: center;
    justify-content: center;
    color: var(--text-color-primary);
  }

  .control-right {
    display: flex;
    flex: 1;
    align-items: center;
    justify-content: flex-end;
  }
}

.side-panel {
  position: absolute;
  top: 0;
  right: 0;
  box-sizing: border-box;
  width: 400px;
  height: 100%;
  transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  transform: translateX(100%);

  &-visible {
    transform: translateX(0);
  }
}
</style>
