// Web/roomkit/vue3/RoomKit/components/StartRoomButtonH5/index.vue
<template>
  <div class="room-button">
    <TUIButton
      class="button"
      size="large"
      type="primary"
      :icon="IconCreateRoom"
      @click="handleStartRoom"
    >
      {{ t('Button.CreateRoom') }}
    </TUIButton>
  </div>
</template>

<script setup lang="ts">
import { IconCreateRoom, TUIButton, useUIKit } from '@tencentcloud/uikit-base-component-vue3';

const { t } = useUIKit();

const emit = defineEmits(['start-room']);

const handleStartRoom = () => {
  emit('start-room');
};
</script>

<style lang="scss" scoped>
.room-button {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;

  .button {
    width: 100%;
    height: 100%;
  }
}
</style>

// Web/roomkit/react/RoomKit/components/StartRoomButtonH5/StartRoomButtonH5.tsx
import { Button, IconCreateRoom, useUIKit } from '@tencentcloud/uikit-base-component-react';
import classNames from 'classnames';
import styles from './StartRoomButtonH5.module.scss';

export interface StartRoomButtonH5Props {
  onStartRoom?: () => void;
  className?: string;
}

export function StartRoomButtonH5({ onStartRoom, className }: StartRoomButtonH5Props) {
  const { t } = useUIKit();

  return (
    <div className={classNames(styles.roomButton, className)}>
      <Button
        className={styles.button}
        size="large"
        type="primary"
        icon={<IconCreateRoom />}
        onClick={() => onStartRoom?.()}
      >
        {t('Button.CreateRoom')}
      </Button>
    </div>
  );
}
