// Web/example/vite-vue3-ts/src/App.vue
<template>
  <UIKitProvider :theme="initialTheme" :language="initialLanguage">
    <div id="app">
      <router-view />
    </div>
  </UIKitProvider>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import { conference, useRoomInvitation, useRoomInvitationH5, RoomEvent } from '@tencentcloud/roomkit-web-vue3';
import { TUIMessageBox, UIKitProvider, useUIKit } from '@tencentcloud/uikit-base-component-vue3';
import { useRoute, useRouter } from 'vue-router';
import { isPC } from './utils/utils';

const { t } = useUIKit();
const initialTheme = ref(localStorage.getItem('tuiRoom-theme') || 'light');
const initialLanguage = ref(localStorage.getItem('tuiRoom-language') || '');

const router = useRouter();
const route = useRoute();

if (!isPC) {
  useRoomInvitationH5({
    onAcceptCall: (params) => {
      router.push({
        path: '/room',
        query: params,
      });
    },
  });
} else {
  useRoomInvitation({
    onAcceptCall: (params) => {
      router.push({
        path: '/room',
        query: params,
      });
    },
  });
}

const onLoginExpired = () => {
  TUIMessageBox.alert({
    title: t('Login.Expired'),
    content: t('Login.ExpiredDescription'),
  });
  router.replace({ path: '/login' });
};
const onKickedOffline = () => {
  TUIMessageBox.alert({
    title: t('Login.KickedOffline'),
    content: t('Login.KickedOfflineDescription'),
  });
  router.replace({ path: '/login' });
};
const bindEvent = () => {
  conference.on(RoomEvent.USER_SIG_EXPIRED, onLoginExpired);
  conference.on(RoomEvent.KICKED_OFFLINE, onKickedOffline);
};
const unbindEvent = () => {
  conference.off(RoomEvent.USER_SIG_EXPIRED, onLoginExpired);
  conference.off(RoomEvent.KICKED_OFFLINE, onKickedOffline);
};

onMounted(async () => {
  bindEvent();
  await router.isReady();
  if (route.path === '/login') {
    return;
  }
  const storedData = sessionStorage.getItem('tuiRoom-userInfo') || '{}';
  const userInfo = JSON.parse(storedData);
  try {
    await conference.login({
      userId: userInfo.userID,
      userSig: userInfo.userSig,
      sdkAppId: userInfo.SDKAppID,
    });
  } catch (error: any) {
    console.error('Login failed:', error);
    sessionStorage.removeItem('tuiRoom-userInfo');
    router.replace({ path: '/login', query: { redirect: route.fullPath } });
  }
});

onUnmounted(() => {
  unbindEvent();
});

</script>

<style lang="scss">
@use './styles/base.scss';
</style>

// Web/example/vite-react-ts/src/App.tsx
import { useEffect, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import {
  TUIMessageBox,
  UIKitProvider,
  useUIKit,
} from '@tencentcloud/uikit-base-component-react';
import {
  RoomEvent,
  conference,
  useRoomInvitation,
} from '@tencentcloud/roomkit-web-react';
import AppRouter from '@/router';
import '@/styles/base.scss';

const InnerApp = () => {
  const { t } = useUIKit();
  const navigate = useNavigate();
  const location = useLocation();
  const bootstrappedRef = useRef(false);

  const roomInvitation = useRoomInvitation({
    onAcceptCall: ({ roomId, password, roomType }) => {
      const search = new URLSearchParams();
      search.set('roomId', roomId);
      if (password) search.set('password', password);
      if (roomType !== undefined && roomType !== null) {
        search.set('roomType', String(roomType));
      }
      navigate(`/room?${search.toString()}`);
    },
  });

  useEffect(() => {
    const onLoginExpired = () => {
      TUIMessageBox.alert({
        title: t('Login.Expired'),
        content: t('Login.ExpiredDescription'),
      });
      navigate('/login', { replace: true });
    };
    const onKickedOffline = () => {
      TUIMessageBox.alert({
        title: t('Login.KickedOffline'),
        content: t('Login.KickedOfflineDescription'),
      });
      navigate('/login', { replace: true });
    };
    conference.on(RoomEvent.USER_SIG_EXPIRED, onLoginExpired);
    conference.on(RoomEvent.KICKED_OFFLINE, onKickedOffline);
    return () => {
      conference.off(RoomEvent.USER_SIG_EXPIRED, onLoginExpired);
      conference.off(RoomEvent.KICKED_OFFLINE, onKickedOffline);
    };
  }, [navigate, t]);

  useEffect(() => {
    if (bootstrappedRef.current) return;
    bootstrappedRef.current = true;

    if (location.pathname === '/login') return;

    const storedData = sessionStorage.getItem('tuiRoom-userInfo') || '{}';
    const userInfo = JSON.parse(storedData);
    if (!userInfo?.userID) return;

    conference
      .login({
        userId: userInfo.userID,
        userSig: userInfo.userSig,
        sdkAppId: userInfo.SDKAppID,
      })
      .catch((error: any) => {
        console.error('Login failed:', error);
        sessionStorage.removeItem('tuiRoom-userInfo');
        const redirect = encodeURIComponent(
          `${location.pathname}${location.search}`
        );
        navigate(`/login?redirect=${redirect}`, { replace: true });
      });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div id="app">
      <AppRouter />
      {roomInvitation}
    </div>
  );
};

export default function App() {
  const [initialTheme] = useState(
    () => localStorage.getItem('tuiRoom-theme') || 'light'
  );
  const [initialLanguage] = useState(
    () => localStorage.getItem('tuiRoom-language') || ''
  );

  return (
    <UIKitProvider
      theme={initialTheme as any}
      language={initialLanguage as any}
    >
      <InnerApp />
    </UIKitProvider>
  );
}
