// Web/roomkit/vue3/RoomKit/components/RoomChatH5/CustomMessage.vue
<template>
  <div class="custom-message-container">
    <Message
      v-bind="$attrs"
      :nick="userName"
      :message="message"
      :removeAvatar="true"
    />
  </div>
</template>

<script lang="ts" setup>
import { computed } from 'vue';
import { Message } from 'tuikit-atomicx-vue3/chat';
import { useRoomParticipantState } from 'tuikit-atomicx-vue3/room';
import type { MessageInfo } from 'tuikit-atomicx-vue3/chat';

interface Props {
  message: MessageInfo;
}
const props = defineProps<Props>();

const { participantList } = useRoomParticipantState();
const sender = computed(() => props.message.from);
const senderUserId = computed(() => sender.value?.userID || '');
const userName = computed(() => {
  const participant = participantList.value.find(
    p => p.userId === senderUserId.value,
  );
  return (
    participant?.nameCard
    || participant?.userName
    || participant?.userId
    || sender.value?.nickname
    || sender.value?.userID
  );
});
</script>

<style lang="scss" scoped>
.custom-message-container {
  width: 100%;

  .custom-message-nick {
    color: var(--text-color-secondary);
    font-weight: 400;
    font-size: 14px;
    line-height: 22px;
    margin-bottom: 4px;
  }

  .self {
    text-align: right;
  }
}
</style>

// Web/roomkit/react/RoomKit/components/RoomChatH5/CustomMessage.tsx
import { useMemo } from 'react';
import type { ComponentProps } from 'react';
import { MessageH5 } from 'tuikit-atomicx-react/chat';
import { useRoomParticipantState } from 'tuikit-atomicx-react/room';

type CustomMessageProps = ComponentProps<typeof MessageH5>;

// Vue reference: RoomChatH5/CustomMessage.vue.
// Must wrap MessageH5 (not PC Message) so long-press actions use H5
// MessageActionDropdown styles (100px width, item dividers, icon colors).
export function CustomMessage(props: CustomMessageProps) {
  const { message, ...rest } = props;
  const { participantList } = useRoomParticipantState();

  const senderUserId = (message.from as { userID?: string } | undefined)?.userID ?? '';
  const senderNick = (message.from as { nickname?: string } | undefined)?.nickname ?? '';

  const nick = useMemo(() => {
    const participant = participantList.find(p => p.userId === senderUserId);
    return (
      participant?.nameCard
      || participant?.userName
      || participant?.userId
      || senderNick
      || senderUserId
    );
  }, [participantList, senderUserId, senderNick]);

  return (
    <div style={{ width: '100%' }}>
      <MessageH5 {...rest} nick={nick} message={message} removeAvatar />
    </div>
  );
}
