// Web/example/atomicx-vite-vue3-ts/src/views/login.vue
<template>
  <div class="login-container">
    <Login
      class="login-widget"
      v-bind="{
        SDKAppID: SDKAPPID,
        generatorUserSig: genTestUserSig,
        onLoginCallback: handleLogin
      }"
    />
  </div>
</template>

<script setup lang="ts">
import { useLoginState, useRoomModal } from 'tuikit-atomicx-vue3/room';
import { useRouter, useRoute } from 'vue-router';
import Login from '../components/LoginUserID/index.vue';
import { SDKAPPID, genTestUserSig } from '../config/basic-info-config';
import { deepClone } from '../utils/utils';

const { login } = useLoginState();
const { handleErrorWithModal } = useRoomModal();

const router = useRouter();
const route = useRoute();

const handleLogin = async (userInfo: {
  SDKAppID: number;
  userID: string;
  userSig: string;
}) => {
  try {
    await login({
      userId: userInfo.userID,
      userSig: userInfo.userSig,
      sdkAppId: userInfo.SDKAppID,
    });
    localStorage.setItem('tuiRoom-userInfo', JSON.stringify(userInfo));
    const currentQuery = deepClone(route.query);
    router.push({ path: route.query.from as string || '/home', query: currentQuery });
  } catch (error: any) {
    console.error('Login failed:', error.code);
    handleErrorWithModal(error);
  }
};
</script>

<style scoped>
.login-container {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 100%;
  background: url('../assets/background-black.png') no-repeat center center;
  background-color: black;
  background-size: cover;

  @media screen and (orientation: portrait), (orientation: landscape) {
    :deep(.phone-prefix) {
      min-width: 30px;
    }
  }
}
</style>

// Web/example/vite-react-ts/src/views/login.tsx
import {
  TUIMessageBox,
  useUIKit,
} from '@tencentcloud/uikit-base-component-react';
import { Login, LoginModel } from '@tencentcloud/uikit-base-widget-react';
import { conference } from '@tencentcloud/roomkit-web-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { SDKAPPID, genTestUserSig } from '../config/basic-info-config';
import './login.scss';

interface LoginCallbackInfo {
  SDKAppID: number;
  userID: string;
  userSig: string;
}

export default function LoginView() {
  const { theme = 'light', t } = useUIKit();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  const handleLogin = async (userInfo: LoginCallbackInfo) => {
    if (!SDKAPPID) {
      TUIMessageBox.alert({
        title: t('Login.Error'),
        content: t('Login.PleaseConfigureSDKAPPID'),
      });
      return;
    }
    try {
      await conference.login({
        userId: userInfo.userID,
        userSig: userInfo.userSig,
        sdkAppId: userInfo.SDKAppID,
      });
      localStorage.setItem('tuiRoom-userInfo', JSON.stringify(userInfo));

      const redirect = searchParams.get('redirect');
      if (redirect) {
        navigate(redirect);
        return;
      }

      const nextParams = new URLSearchParams(searchParams);
      const from = nextParams.get('from');
      nextParams.delete('from');
      const search = nextParams.toString();
      navigate({
        pathname: from || '/home',
        search: search ? `?${search}` : '',
      });
    } catch (error: any) {
      console.error('Login failed:', error?.code);
    }
  };

  return (
    <div className={`login-container ${theme}`}>
      <Login
        className="login-widget"
        SDKAppID={SDKAPPID}
        model={LoginModel.userID}
        generatorUserSig={genTestUserSig}
        onLoginCallback={handleLogin}
      />
    </div>
  );
}
