// Web/roomkit/react/RoomKit/components/SwitchCameraButtonH5/SwitchCameraButtonH5.tsx
import { useRef } from 'react';
import { IconCameraSwitch } from '@tencentcloud/uikit-base-component-react';
import { MirrorType, useDeviceState } from 'tuikit-atomicx-react/room';

export function SwitchCameraButtonH5() {
  const { isFrontCamera, switchCamera, localMirrorType, switchMirror } = useDeviceState();

  const lastLocalFrontCameraMirrorRef = useRef<MirrorType>(
    isFrontCamera ? localMirrorType : MirrorType.Auto,
  );

  const handleSwitchCamera = async () => {
    await switchCamera({ isFrontCamera: !isFrontCamera });
    const newIsFrontCamera = !isFrontCamera;
    if (newIsFrontCamera) {
      await switchMirror({ mirror: lastLocalFrontCameraMirrorRef.current });
    } else {
      lastLocalFrontCameraMirrorRef.current = localMirrorType;
      await switchMirror({ mirror: MirrorType.Disable });
    }
  };

  return <IconCameraSwitch size="20" onClick={handleSwitchCamera} />;
}

// Web/roomkit/vue3/RoomKit/components/SwitchCameraButtonH5/index.vue
<template>
  <IconCameraSwitch size="20" @click="handleSwitchCamera" />
</template>
<script setup lang="ts">
import { IconCameraSwitch } from '@tencentcloud/uikit-base-component-vue3';
import { useDeviceState, MirrorType } from 'tuikit-atomicx-vue3/room';

const { isFrontCamera, switchCamera, localMirrorType, switchMirror } = useDeviceState();

let lastLocalFrontCameraMirror = isFrontCamera.value ? localMirrorType.value : MirrorType.Auto;

const handleSwitchCamera = async () => {
  await switchCamera({ isFrontCamera: !isFrontCamera.value });
  const newIsFrontCamera = isFrontCamera.value;
  if (newIsFrontCamera) {
    await switchMirror({ mirror: lastLocalFrontCameraMirror });
  } else {
    lastLocalFrontCameraMirror = localMirrorType.value;
    await switchMirror({ mirror: MirrorType.Disable });
  }
};
</script>
