// Web/roomkit/vue3/RoomKit/components/SettingButtonH5/index.vue
<template>
  <IconButtonH5 :title="t('Settings.Title')" @click="isSettingPopupVisible = true">
    <IconSetting size="24" />
  </IconButtonH5>

  <SettingPopup
    v-if="isSettingPopupVisible"
    @close="isSettingPopupVisible = false"
  />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import {
  IconSetting,
  useUIKit,
} from '@tencentcloud/uikit-base-component-vue3';
import IconButtonH5 from '../base/IconButtonH5.vue';
import SettingPopup from './SettingPopup.vue';

const { t } = useUIKit();

const isSettingPopupVisible = ref(false);
</script>

// Web/roomkit/react/RoomKit/components/SettingButtonH5/SettingButtonH5.tsx
import { useState } from 'react';
import {
  IconSetting,
  useUIKit,
} from '@tencentcloud/uikit-base-component-react';
import { IconButtonH5 } from '../base/IconButtonH5';
import { SettingPopup } from './SettingPopup';

// Vue reference: SettingButtonH5/index.vue.
export function SettingButtonH5() {
  const { t } = useUIKit();
  const [visible, setVisible] = useState(false);
  return (
    <>
      <IconButtonH5 title={t('Settings.Title')} onClick={() => setVisible(true)}>
        <IconSetting size="24" />
      </IconButtonH5>
      {visible && (
        <SettingPopup visible={visible} onVisibleChange={setVisible} />
      )}
    </>
  );
}
