// Web/roomkit/vue3/RoomKit/views/PreConferenceViewH5/JoinRoomView.vue
<template>
  <div :class="['join-room-container-h5', theme]">
    <header class="header-h5">
      <IconBack
        size="22"
        class="back-button"
        @click="handleGoBack"
      />
      <h1 class="title">
        {{ t('Button.JoinRoom') }}
      </h1>
      <div class="header-placeholder" />
    </header>

    <main class="main-h5">
      <div class="room-info">
        <div class="form-item">
          <TUIInput
            v-model="roomId"
            :label="t('Room.RoomId')"
            class="form-input"
            :placeholder="t('Room.EnterRoomId')"
            max-length="20"
          />
        </div>

        <div class="form-item">
          <span class="form-label">{{ t('User.Nickname') }}</span>
          <span class="form-input">{{
            loginUserInfo?.userName || loginUserInfo?.userId
          }}</span>
        </div>
      </div>

      <div class="room-settings">
        <div class="form-item toggle-item">
          <span class="form-label">{{ t('Room.OpenMicrophone') }}</span>
          <TUISwitch v-model="openMicrophone" size="large" />
        </div>

        <div class="form-item toggle-item">
          <span class="form-label">{{ t('Room.OpenCamera') }}</span>
          <TUISwitch v-model="openCamera" size="large" />
        </div>
      </div>
    </main>
    <div class="footer-h5">
      <TUIButton
        type="primary"
        class="join-button"
        :loading="loading"
        @click="handleJoinRoom"
      >
        {{ t('Button.JoinRoom') }}
      </TUIButton>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { TUIErrorCode } from '@tencentcloud/tuiroom-engine-js';
import {
  useUIKit,
  TUIToast,
  TUIMessageBox,
  IconBack,
  TUISwitch,
  TUIButton,
  TUIInput,
} from '@tencentcloud/uikit-base-component-vue3';
import { useRoomState, useLoginState, RoomType } from 'tuikit-atomicx-vue3/room';

interface Emits {
  (e: 'join-room', roomId: string): void;
  (e: 'back'): void;
  (e: 'camera-preference-change', isOpen: boolean): void;
  (e: 'microphone-preference-change', isOpen: boolean): void;
}
interface Props {
  cameraPreference?: boolean;
  microphonePreference?: boolean;
}

const emit = defineEmits<Emits>();
const props = withDefaults(defineProps<Props>(), {
  cameraPreference: true,
  microphonePreference: true,
});

const { t, theme, language } = useUIKit();
const { loginUserInfo } = useLoginState();
const { getRoomInfo } = useRoomState();

const roomId = ref('');
const openMicrophone = ref(props.microphonePreference);
const openCamera = ref(props.cameraPreference);
const loading = ref(false);

watch(openMicrophone, (newVal) => {
  emit('microphone-preference-change', newVal);
});

watch(openCamera, (newVal) => {
  emit('camera-preference-change', newVal);
});

const labelWidth = computed(() => {
  if (language.value === 'en-US') {
    return '115px';
  }
  return '80px';
});

const handleGoBack = () => {
  emit('back');
};

const getTargetRoomInfo = async (id: string) => {
  try {
    return await getRoomInfo({ roomId: id });
  } catch (error: unknown) {
    if (
      error
      && typeof error === 'object'
      && 'code' in error
      && error.code === TUIErrorCode.ERR_ROOM_ID_NOT_EXIST
    ) {
      return null;
    }
    throw error;
  }
};

const handleJoinRoom = async () => {
  loading.value = true;
  if (!roomId.value.trim()) {
    TUIToast.error({ message: t('Room.RoomIdRequired') });
    return;
  }

  try {
    const normalizedRoomId = roomId.value.trim();
    const roomInfo = await getTargetRoomInfo(normalizedRoomId);

    if (!roomInfo) {
      TUIMessageBox.alert({
        type: 'error',
        modal: false,
        showClose: false,
        title: t('Room.Alert'),
        content: t('Room.RoomNotFound'),
      });
      return;
    }

    const isWebinarRoom = roomInfo.roomType === RoomType.Webinar;
    if (isWebinarRoom) {
      TUIMessageBox.alert({
        type: 'error',
        modal: false,
        showClose: false,
        title: t('Room.Alert'),
        content: t('Room.H5NotSupportWebinar'),
      });
      return;
    }

    emit('join-room', normalizedRoomId);
  } catch (error: unknown) {
    const errorMessage
      = error && typeof error === 'object' && 'message' in error
        ? String(error.message)
        : t('Room.JoinRoomError');
    TUIToast.error({ message: errorMessage });
  } finally {
    loading.value = false;
  }
};
</script>

<style lang="scss" scoped>
@mixin card-container-h5 {
  border-radius: 10px;
  background-color: var(--bg-color-operate);
  display: flex;
  flex-direction: column;
  gap: 20px;
  padding: 16px;
}

@mixin font-text-h5 {
  font-family:
    PingFang SC,
    -apple-system,
    BlinkMacSystemFont,
    sans-serif;
  font-weight: 400;
  font-size: 16px;
  line-height: 1.5;
  color: var(--text-color-primary);
}

@mixin active-state {
  transition: opacity 0.2s ease;

  &:active {
    opacity: 0.6;
  }
}

.join-room-container-h5 {
  height: 100%;
  padding: env(safe-area-inset-top) env(safe-area-inset-right)
    env(safe-area-inset-bottom) env(safe-area-inset-left);
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  background-color: var(--bg-color-default);
  @include font-text-h5;
  -webkit-tap-highlight-color: transparent;

  @supports (height: 100dvh) {
    height: 100dvh;
  }
}

.header-h5 {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px;
  background-color: var(--bg-color-operate);

  .back-button {
    width: 40px;
    height: 40px;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    @include active-state;
  }

  .title {
    flex: 1;
    text-align: center;
    font-size: 17px;
    font-weight: 600;
    color: var(--text-color-primary);
    margin: 0;
  }

  .header-placeholder {
    width: 40px;
  }
}

.main-h5 {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 16px;
  overflow-y: auto;
}

.footer-h5 {
  padding: 16px;
  background-color: var(--bg-color-default);
}

.form-item {
  display: flex;
  align-items: center;
  min-height: 32px;

  &.toggle-item {
    justify-content: space-between;
  }

  .form-label {
    flex-shrink: 0;
    min-width: v-bind(labelWidth);
    margin-right: 12px;
  }

  .form-input {
    flex: 1;
  }
}

.room-info,
.room-settings {
  @include card-container-h5;
}

.join-button {
  width: 100%;
  height: 50px;
  @include active-state;

  &:active {
    opacity: 0.8;
  }
}

:deep(.tui-input--mobile.tui-input--with-label) {
  padding: 0 !important;
  .tui-input__label {
    min-width: v-bind(labelWidth);
  }
}
</style>

// Web/roomkit/react/RoomKit/views/PreConferenceViewH5/JoinRoomView.tsx
import { useEffect, useRef, useState } from 'react';
import { TUIErrorCode } from '@tencentcloud/tuiroom-engine-js';
import {
  Button,
  IconBack,
  Input,
  MessageBox,
  Switch,
  Toast,
  useUIKit,
} from '@tencentcloud/uikit-base-component-react';
import classNames from 'classnames';
import {
  RoomType,
  useLoginState,
  useRoomState,
} from 'tuikit-atomicx-react/room';
import styles from './JoinRoomView.module.scss';

export interface JoinRoomViewProps {
  cameraPreference?: boolean;
  microphonePreference?: boolean;
  onJoinRoom?: (roomId: string) => void;
  onBack?: () => void;
  onCameraPreferenceChange?: (isOpen: boolean) => void;
  onMicrophonePreferenceChange?: (isOpen: boolean) => void;
}

export function JoinRoomView({
  cameraPreference = true,
  microphonePreference = true,
  onJoinRoom,
  onBack,
  onCameraPreferenceChange,
  onMicrophonePreferenceChange,
}: JoinRoomViewProps) {
  const { t, theme, language } = useUIKit();
  const { loginUserInfo } = useLoginState();
  const { getRoomInfo } = useRoomState();

  const [roomId, setRoomId] = useState('');
  const [openMicrophone, setOpenMicrophone] = useState(microphonePreference);
  const [openCamera, setOpenCamera] = useState(cameraPreference);
  const [loading, setLoading] = useState(false);

  const onMicChangeRef = useRef(onMicrophonePreferenceChange);
  useEffect(() => {
    onMicChangeRef.current = onMicrophonePreferenceChange;
  }, [onMicrophonePreferenceChange]);

  const onCameraChangeRef = useRef(onCameraPreferenceChange);
  useEffect(() => {
    onCameraChangeRef.current = onCameraPreferenceChange;
  }, [onCameraPreferenceChange]);

  const isFirstMicWatch = useRef(true);
  useEffect(() => {
    if (isFirstMicWatch.current) {
      isFirstMicWatch.current = false;
      return;
    }
    onMicChangeRef.current?.(openMicrophone);
  }, [openMicrophone]);

  const isFirstCameraWatch = useRef(true);
  useEffect(() => {
    if (isFirstCameraWatch.current) {
      isFirstCameraWatch.current = false;
      return;
    }
    onCameraChangeRef.current?.(openCamera);
  }, [openCamera]);

  const labelWidth = language === 'en-US' ? '115px' : '80px';

  const getTargetRoomInfo = async (id: string) => {
    try {
      return await getRoomInfo({ roomId: id });
    } catch (error) {
      const err = error as { code?: number };
      if (err.code === TUIErrorCode.ERR_ROOM_ID_NOT_EXIST) {
        return null;
      }
      throw error;
    }
  };

  const handleJoinRoom = async () => {
    setLoading(true);
    if (!roomId.trim()) {
      Toast.error({ message: t('Room.RoomIdRequired') });
      // Vue H5 has a latent bug here: it early-returns without clearing
      // `loading.value = true`, leaving the button spinner stuck. Fix that
      // in-place on the React side.
      setLoading(false);
      return;
    }

    try {
      const normalizedRoomId = roomId.trim();
      const roomInfo = await getTargetRoomInfo(normalizedRoomId);

      if (!roomInfo) {
        MessageBox.alert({
          type: 'error',
          modal: false,
          showClose: false,
          title: t('Room.Alert'),
          content: t('Room.RoomNotFound'),
        });
        return;
      }

      if (roomInfo.roomType === RoomType.Webinar) {
        MessageBox.alert({
          type: 'error',
          modal: false,
          showClose: false,
          title: t('Room.Alert'),
          content: t('Room.H5NotSupportWebinar'),
        });
        return;
      }

      onJoinRoom?.(normalizedRoomId);
    } catch (error) {
      const message =
        error && typeof error === 'object' && 'message' in error
          ? String((error as { message: unknown }).message)
          : t('Room.JoinRoomError');
      Toast.error({ message });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={classNames(styles.joinRoomContainerH5, theme === 'dark' ? styles.themeDark : styles.themeLight)}>
      <header className={styles.headerH5}>
        <IconBack
          size="22"
          className={styles.backButton}
          onClick={() => onBack?.()}
        />
        <h1 className={styles.title}>{t('Button.JoinRoom')}</h1>
        <div className={styles.headerPlaceholder} />
      </header>

      <main className={styles.mainH5}>
        <div className={styles.roomInfo}>
          <div className={styles.formItem}>
            <span
              className={styles.formLabel}
              style={{ minWidth: labelWidth }}
            >
              {t('Room.RoomId')}
            </span>
            <Input
              value={roomId}
              border={false}
              className={styles.roomIdInput}
              placeholder={t('Room.EnterRoomId')}
              maxLength={20}
              onChange={(e) => setRoomId(e.target.value)}
            />
          </div>

          <div className={styles.formItem}>
            <span
              className={styles.formLabel}
              style={{ minWidth: labelWidth }}
            >
              {t('User.Nickname')}
            </span>
            <span className={styles.formInput}>
              {loginUserInfo?.userName || loginUserInfo?.userId}
            </span>
          </div>
        </div>

        <div className={styles.roomSettings}>
          <div className={classNames(styles.formItem, styles.toggleItem)}>
            <span
              className={styles.formLabel}
              style={{ minWidth: labelWidth }}
            >
              {t('Room.OpenMicrophone')}
            </span>
            <Switch
              value={openMicrophone}
              size="large"
              onChange={setOpenMicrophone}
            />
          </div>
          <div className={classNames(styles.formItem, styles.toggleItem)}>
            <span
              className={styles.formLabel}
              style={{ minWidth: labelWidth }}
            >
              {t('Room.OpenCamera')}
            </span>
            <Switch value={openCamera} size="large" onChange={setOpenCamera} />
          </div>
        </div>
      </main>

      <div className={styles.footerH5}>
        <Button
          type="primary"
          className={styles.joinButton}
          loading={loading}
          onClick={handleJoinRoom}
        >
          {t('Button.JoinRoom')}
        </Button>
      </div>
    </div>
  );
}
