// Web/roomkit/vue3/RoomKit/components/CloudRecording/CloudRecordingButtonH5.vue
<template>
  <IconButtonH5
    :title="isRecording ? t('CloudRecording.RecordingLabel') : t('CloudRecording.RecordLabel')"
    @click="handleRecordingClick"
  >
    <IconRecording v-if="isRecording" size="24" />
    <IconStartRecord v-else size="24" />
  </IconButtonH5>
</template>

<script setup lang="ts">
import { IconRecording, IconStartRecord, useUIKit } from '@tencentcloud/uikit-base-component-vue3';
import IconButtonH5 from '../base/IconButtonH5.vue';
import { useCloudRecordingAction } from './useCloudRecordingAction';

const { t } = useUIKit();
const { isRecording, handleRecordingClick } = useCloudRecordingAction();
</script>

// Web/roomkit/react/RoomKit/components/CloudRecordingButtonH5/CloudRecordingButtonH5.tsx
import {
  IconRecording,
  IconStartRecord,
  useUIKit,
} from '@tencentcloud/uikit-base-component-react';
import { IconButtonH5 } from '../base/IconButtonH5';
import { useCloudRecordingAction } from '../CloudRecording/useCloudRecordingAction';

// Vue reference: CloudRecording/CloudRecordingButtonH5.vue.
export function CloudRecordingButtonH5() {
  const { t } = useUIKit();
  const { isRecording, handleRecordingClick } = useCloudRecordingAction();
  return (
    <IconButtonH5
      title={
        isRecording
          ? t('CloudRecording.RecordingLabel')
          : t('CloudRecording.RecordLabel')
      }
      onClick={handleRecordingClick}
    >
      {isRecording ? <IconRecording size="24" /> : <IconStartRecord size="24" />}
    </IconButtonH5>
  );
}
