// Web/roomkit/vue3/RoomKit/components/RoomParticipantList/RoomActionH5.vue
<template>
  <div v-if="canOperate" class="room-action-h5-container">
    <TUIButton
      type="primary"
      color="gray"
      class="action-button"
      @click="roomAudioAction.handler"
    >
      {{ roomAudioAction.label }}
    </TUIButton>
    <TUIButton
      type="primary"
      color="gray"
      class="action-button"
      @click="roomVideoAction.handler"
    >
      {{ roomVideoAction.label }}
    </TUIButton>
    <TUIButton
      v-if="moreControlList.length > 0"
      type="primary"
      color="gray"
      class="action-button"
      @click="showMorePopup = true"
    >
      {{ t('ParticipantList.More') }}
    </TUIButton>

    <!-- More actions popup -->
    <TUIPopup
      :visible="showMorePopup"
      @update:visible="showMorePopup = $event"
    >
      <PopUpArrowDown @click="showMorePopup = false" />
      <div class="more-actions-content">
        <div
          v-for="item in moreControlList"
          :key="item.key"
          class="action-item"
          @click="handleMoreActionClick(item.handler)"
        >
          <TUIIcon
            v-if="item.icon"
            :icon="item.icon"
            size="20"
            class="action-icon"
          />
          <span class="action-text">{{ item.label }}</span>
        </div>
      </div>
    </TUIPopup>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import {
  TUIButton,
  useUIKit,
  TUIIcon,
  TUIPopup,
} from '@tencentcloud/uikit-base-component-vue3';
import PopUpArrowDown from './PopUpArrowDown.vue';
import useRoomActions from './useRoomAction';

defineOptions({
  name: 'RoomActionH5',
});

const { t } = useUIKit();
const { canOperate, roomActionList } = useRoomActions();

const roomAudioAction = computed(() => roomActionList.value[0]);
const roomVideoAction = computed(() => roomActionList.value[1]);
const moreControlList = computed(() => roomActionList.value.slice(2));

const showMorePopup = ref(false);

function handleMoreActionClick(handler: () => void) {
  handler();
  showMorePopup.value = false;
}
</script>

<style scoped lang="scss">
.room-action-h5-container {
  display: flex;
  align-items: center;
  gap: 12px;
  width: 100%;
  -webkit-tap-highlight-color: transparent;

  .action-button {
    flex: 1;
    min-width: 0;
  }

  .more-arrow {
    margin-left: 4px;
    transform: rotate(180deg);
  }
}

.more-actions-content {
  display: flex;
  flex-direction: column;
  padding: 12px 16px;

  .action-item {
    display: flex;
    align-items: center;
    cursor: pointer;
    transition: background 0.2s ease;
    gap: 12px;
    color: var(--text-color-secondary);

    &:active {
      background: var(--list-color-hover);
    }

    .action-icon {
      flex-shrink: 0;
    }

    .action-text {
      flex: 1;
      font-size: 16px;
      font-weight: 400;
      line-height: 22px;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
  }
}
</style>

// Web/roomkit/react/RoomKit/components/RoomParticipantList/RoomActionH5.tsx
import { useState } from 'react';
import {
  Button,
  Popup,
  useUIKit,
} from '@tencentcloud/uikit-base-component-react';
import { useRoomActions } from './useRoomAction';
import { PopUpArrowDown } from '../base/PopUpArrowDown';
import styles from './RoomActionH5.module.scss';

// Vue reference: RoomParticipantList/RoomActionH5.vue (136 lines).
export function RoomActionH5() {
  const { t } = useUIKit();
  const { canOperate, roomActionList } = useRoomActions();

  const [showMorePopup, setShowMorePopup] = useState(false);

  if (!canOperate) {
    return null;
  }

  const roomAudioAction = roomActionList[0];
  const roomVideoAction = roomActionList[1];
  const moreControlList = roomActionList.slice(2);

  const handleMoreActionClick = (handler: () => void) => {
    handler();
    setShowMorePopup(false);
  };

  return (
    <div className={styles.roomActionH5Container}>
      <Button
        type="primary"
        color="gray"
        className={styles.actionButton}
        onClick={roomAudioAction?.handler}
      >
        {roomAudioAction?.label}
      </Button>
      <Button
        type="primary"
        color="gray"
        className={styles.actionButton}
        onClick={roomVideoAction?.handler}
      >
        {roomVideoAction?.label}
      </Button>
      {moreControlList.length > 0 && (
        <Button
          type="primary"
          color="gray"
          className={styles.actionButton}
          onClick={() => setShowMorePopup(true)}
        >
          {t('ParticipantList.More')}
        </Button>
      )}

      <Popup visible={showMorePopup} onUpdateVisible={setShowMorePopup}>
        <PopUpArrowDown onClick={() => setShowMorePopup(false)} />
        <div className={styles.moreActionsContent}>
          {moreControlList.map((item) => {
            const IconComponent = item.icon;
            return (
              <div
                key={item.key}
                className={styles.actionItem}
                onClick={() => handleMoreActionClick(item.handler)}
              >
                {IconComponent && (
                  <span className={styles.actionIcon}>
                    <IconComponent />
                  </span>
                )}
                <span className={styles.actionText}>{item.label}</span>
              </div>
            );
          })}
        </div>
      </Popup>
    </div>
  );
}
