// Web/roomkit/react/RoomKit/components/MicButtonH5/MicButtonH5.tsx
import type { CSSProperties } from 'react';
import { useState } from 'react';
import { IconUnSupport, Toast, useUIKit } from '@tencentcloud/uikit-base-component-react';
import {
  DeviceError,
  DeviceStatus,
  DeviceType,
  RoomParticipantRole,
  useDeviceState,
  useRoomParticipantState,
  useRoomState,
} from 'tuikit-atomicx-react/room';
import { conference } from '../../adapter/conference';
import { InterceptorAction } from '../../adapter/type';
import { handleMediaCaptureError } from '../../hooks/useMediaCaptureError';
import { IconButtonH5 } from '../base/IconButtonH5';
import { AudioIcon } from '../MicButton/AudioIcon';
import styles from './MicButtonH5.module.scss';

export interface MicButtonH5Props {
  showDescription?: boolean;
  customStyle?: CSSProperties;
  /**
   * Force-render the "permission denied" red-slash badge. Set by parent views
   * that listen to TUIRoomEvents.onError -1105 out-of-band.
   */
  hasPermissionError?: boolean;
  /** Fired when the user taps the button, so the parent can clear its denial flag. */
  onRetryPermission?: () => void;
}

export function MicButtonH5({
  showDescription = true,
  customStyle,
  hasPermissionError = false,
  onRetryPermission,
}: MicButtonH5Props) {
  const { t } = useUIKit();
  const { currentRoom } = useRoomState();
  const {
    currentMicVolume,
    testingMicVolume,
    microphoneStatus,
    microphoneLastError,
    isMicrophoneTesting,
    openLocalMicrophone,
    startMicrophoneTest,
    stopMicrophoneTest,
  } = useDeviceState();
  const {
    localParticipant,
    muteMicrophone,
    unmuteMicrophone,
  } = useRoomParticipantState();

  const [isProcessing, setIsProcessing] = useState(false);

  const isOwnerOrAdmin =
    localParticipant?.role === RoomParticipantRole.Owner ||
    localParticipant?.role === RoomParticipantRole.Admin;
  const isMicrophoneOn = microphoneStatus === DeviceStatus.On;
  const isMicrophoneDisabled =
    !isOwnerOrAdmin &&
    !isMicrophoneOn &&
    Boolean(currentRoom?.isAllMicrophoneDisabled);

  // Pre-room preview branch adds `microphoneLastError !== NoError` on top of
  // Vue reference for the same reason as CameraButtonH5: cover the window
  // where atomicx still reports `isMicrophoneTesting=true` after a capture
  // failure. Ensures the mute icon reflects the actual capture state.
  const isMuted = currentRoom
    ? microphoneStatus !== DeviceStatus.On
    : (!isMicrophoneTesting || microphoneLastError !== DeviceError.NoError);

  const hasNotSupportError = microphoneLastError !== DeviceError.NoError;

  const resolveTitle = (): string => {
    if (!showDescription) return '';
    return isMuted ? t('Microphone.Unmute') : t('Microphone.Mute');
  };
  const title = resolveTitle();

  const handleClickIcon = async () => {
    if (isProcessing) return;
    setIsProcessing(true);
    onRetryPermission?.();
    try {
      if (isMicrophoneDisabled) {
        Toast.warning({ message: t('Microphone.Disabled') });
        return;
      }
      if (!currentRoom) {
        if (isMicrophoneTesting) {
          await stopMicrophoneTest();
        } else {
          await startMicrophoneTest({ interval: 200 });
        }
        return;
      }
      if (microphoneStatus === DeviceStatus.On) {
        await conference.executeInterceptor(InterceptorAction.CloseMicrophone, async () => {
          await muteMicrophone();
        });
      } else {
        await conference.executeInterceptor(InterceptorAction.OpenMicrophone, async () => {
          await openLocalMicrophone();
          await unmuteMicrophone();
        });
      }
    } catch (error) {
      handleMediaCaptureError({ error, deviceType: DeviceType.Microphone });
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className={styles.audioControl}>
      <IconButtonH5
        title={title}
        disabled={isMicrophoneDisabled}
        customStyle={customStyle}
        onClick={handleClickIcon}
      >
        <div className={styles.audioIconContainer}>
          <AudioIcon
            audioVolume={isMicrophoneTesting ? testingMicVolume : currentMicVolume}
            isMuted={isMuted}
          />
          {(hasNotSupportError || hasPermissionError) && (
            <IconUnSupport className={styles.unSupportIcon} size="14" />
          )}
        </div>
      </IconButtonH5>
    </div>
  );
}

// Web/roomkit/vue3/RoomKit/components/MicButtonH5/index.vue
<template>
  <div
    v-click-outside="handleHideAudioSettingTab"
    class="audio-control-container"
  >
    <icon-button-h5
      :style="props.customStyle"
      :title="title"
      :disabled="isMicrophoneDisabled"
      @click="handleClickIcon"
    >
      <div class="audio-icon-container">
        <audio-icon
          :audio-volume="isMicrophoneTesting ? testingMicVolume : currentMicVolume"
          :is-muted="isMuted"
        />
        <IconUnSupport
          v-if="hasNotSupportError"
          class="un-support-icon"
          size="14"
        />
      </div>
    </icon-button-h5>
  </div>
</template>

<script setup lang="ts">
import type { Ref } from 'vue';
import { ref, computed } from 'vue';
import { useUIKit, TUIToast, IconUnSupport } from '@tencentcloud/uikit-base-component-vue3';

import { useDeviceState, useRoomState, useRoomParticipantState, RoomParticipantRole, DeviceStatus, DeviceError, DeviceType } from 'tuikit-atomicx-vue3/room';
import { conference } from '../../adapter/conference';
import { InterceptorAction } from '../../adapter/type';
import { handleMediaCaptureError } from '../../hooks/useMediaCaptureError';
import IconButtonH5 from '../base/IconButtonH5.vue';
import vClickOutside from '../base/vClickOutside';
import AudioIcon from './AudioIcon.vue';

interface Props {
  showDescription?: boolean;
  customStyle?: Record<string, string>;
}

const props = withDefaults(defineProps<Props>(), {
  showDescription: true,
  customStyle: () => ({}),
});

const { t } = useUIKit();
const { currentRoom } = useRoomState();
const {
  currentMicVolume,
  testingMicVolume,
  microphoneStatus,
  microphoneLastError,
  isMicrophoneTesting,
  openLocalMicrophone,
  startMicrophoneTest,
  stopMicrophoneTest,
} = useDeviceState();
const { localParticipant, muteMicrophone, unmuteMicrophone } = useRoomParticipantState();

const showAudioSettingTab: Ref<boolean> = ref(false);
const isProcessing = ref(false);

const isMicrophoneDisabled = computed(() => {
  if (localParticipant.value?.role === RoomParticipantRole.Owner || localParticipant.value?.role === RoomParticipantRole.Admin) {
    return false;
  }
  if (microphoneStatus.value === DeviceStatus.On) {
    return false;
  }
  return currentRoom.value?.isAllMicrophoneDisabled;
});

const isMuted = computed(() => {
  if (!currentRoom?.value) {
    return !isMicrophoneTesting.value;
  }
  return microphoneStatus.value !== DeviceStatus.On;
});

const title = computed(() => {
  if (!props.showDescription) {
    return '';
  }
  return isMuted.value ? t('Microphone.Unmute') : t('Microphone.Mute');
});

const hasNotSupportError = computed(() => DeviceError.NoError !== microphoneLastError.value);

async function handleClickIcon() {
  if (isProcessing.value) {
    return;
  }
  isProcessing.value = true;
  try {
    if (isMicrophoneDisabled.value) {
      TUIToast.warning({
        message: t('Microphone.Disabled'),
      });
      return;
    }
    if (!currentRoom.value) {
      if (isMicrophoneTesting.value) {
        await stopMicrophoneTest();
      } else {
        await startMicrophoneTest({ interval: 200 });
      }
      return;
    }
    if (microphoneStatus.value === DeviceStatus.On) {
      await conference.executeInterceptor(InterceptorAction.CloseMicrophone, async () => {
        await muteMicrophone();
      });
    } else {
      await conference.executeInterceptor(InterceptorAction.OpenMicrophone, async () => {
        await openLocalMicrophone();
        await unmuteMicrophone();
      });
    }
  } catch (error: any) {
    handleMediaCaptureError({ error, deviceType: DeviceType.Microphone });
  } finally {
    isProcessing.value = false;
  }
}

function handleHideAudioSettingTab() {
  if (showAudioSettingTab.value) {
    showAudioSettingTab.value = false;
  }
}
</script>

<style lang="scss" scoped>
$audio-tab-width: 305px;

.audio-icon-container {
  position: relative;
}

.un-support-icon {
  position: absolute;
  bottom: 1px;
  right: 1px;
}

.audio-control-container {
  position: relative;
  display: flex;

  .audio-tab {
    position: absolute;
    bottom: calc(100% + 12px);
    left: -5px;
    width: $audio-tab-width;
    box-sizing: border-box;
    padding: 20px 20px 24px;
    background-color: var(--bg-color-dialog);
    border-radius: 8px;
    box-shadow:
      0 2px 4px -3px var(--uikit-color-black-8),
      0 6px 10px 1px var(--uikit-color-black-8),
      0 3px 14px 2px var(--uikit-color-black-8);

    &::before {
      position: absolute;
      bottom: -10px;
      left: 28px;
      content: '';
      border-top: 5px solid var(--bg-color-dialog);
      border-right: 5px solid transparent;
      border-bottom: 5px solid transparent;
      border-left: 5px solid transparent;
    }
  }
}
</style>
