// Web/roomkit/vue3/RoomKit/views/PreConferenceView/PreviewView.vue
<template>
  <div :class="['home-container', theme]">
    <header v-if="mergedUiOptions.showHeader" class="header">
      <div class="header-left">
        <ThemeButton />
      </div>
      <div class="header-right">
        <LanguageButton />
        <LoginUserInfo @logout="handleLogout" />
      </div>
    </header>

    <main class="main">
      <div v-if="mergedUiOptions.showLogo" class="title">
        <div :class="['logo', language]" />
      </div>
      <div class="main-container">
        <div class="room-preview-container">
          <div class="camera-preview-area">
            <div id="room-preview-video" class="video-preview" />
            <div class="attention-info">
              <span
                v-if="!isCameraTesting && !isCameraTestLoading"
                class="off-camera-info"
              >{{ t('Off Camera') }}</span>
              <IconLoading
                v-if="isCameraTestLoading"
                size="36"
                class="loading"
              />
            </div>
          </div>
          <div class="control-container">
            <div class="media-control-region">
              <MicButton />
              <CameraButton cameraTestContainer="room-preview-video" />
            </div>
            <div class="room-control-region">
              <StartRoomButton
                class="button-item"
                @start-room="handleStartRoom"
              />
              <JoinRoomButton
                class="button-item"
                @join-room="handleJoinRoom"
              />
              <ScheduledRoomButton class="button-item" />
            </div>
          </div>
        </div>
        <div class="schedule-list">
          <ScheduledRoomList
            @join-room="handleScheduleJoinRoom"
          />
        </div>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import {
  computed,
  onMounted,
  onBeforeUnmount,
  watch,
} from 'vue';
import TUIRoomEngine, { TUIErrorCode } from '@tencentcloud/tuiroom-engine-js';
import {
  useUIKit,
  IconLoading,
  TUIMessageBox,
  TUIToast,
} from '@tencentcloud/uikit-base-component-vue3';
import { RoomType,
  ScheduledRoomList,
  useDeviceState,
  useRoomState,
  useRoomModal,
} from 'tuikit-atomicx-vue3/room';
import CameraButton from '../../components/CameraButton/index.vue';
import JoinRoomButton from '../../components/JoinRoomButton/index.vue';
import LanguageButton from '../../components/LanguageButton/index.vue';
import LoginUserInfo from '../../components/LoginUserInfo/index.vue';
import MicButton from '../../components/MicButton/index.vue';
import ScheduledRoomButton from '../../components/ScheduledRoomButton/index.vue';
import StartRoomButton from '../../components/StartRoomButton/index.vue';
import ThemeButton from '../../components/ThemeButton/index.vue';

interface Emits {
  (e: 'create-room', roomId: string, roomType: RoomType): void;
  (e: 'join-room', roomId: string, roomType: RoomType): void;
  (e: 'camera-preference-change', isOpen: boolean): void;
  (e: 'microphone-preference-change', isOpen: boolean): void;
  (e: 'logout'): void;
}

interface Props {
  uiOptions?: {
    showHeader?: boolean;
    showLogo?: boolean;
  };
}

const props = withDefaults(defineProps<Props>(), {
  uiOptions: () => ({}),
});

const emit = defineEmits<Emits>();
const { t, theme, language } = useUIKit();
const mergedUiOptions = computed(() => ({
  showHeader: true,
  showLogo: true,
  ...props.uiOptions,
}));

const { getRoomInfo } = useRoomState();
const {
  isMicrophoneTesting,
  isCameraTesting,
  isCameraTestLoading,
  startCameraTest,
  startMicrophoneTest,
  stopCameraTest,
  stopMicrophoneTest,
} = useDeviceState();
const { handleErrorWithModal } = useRoomModal();

watch(isMicrophoneTesting, () => {
  emit('microphone-preference-change', isMicrophoneTesting.value);
});

watch(isCameraTesting, () => {
  emit('camera-preference-change', isCameraTesting.value);
});

const checkRoomExist = async (roomId: string) => {
  try {
    await getRoomInfo({ roomId });
  } catch (error: any) {
    if (error.code === TUIErrorCode.ERR_ROOM_ID_NOT_EXIST) {
      return false;
    }
  }
  return true;
};

const MAX_ROOM_ID_RETRIES = 5;

const generateRoomId = async (roomType: RoomType, retriesLeft = MAX_ROOM_ID_RETRIES): Promise<string> => {
  const roomId = String(Math.floor(Math.random() * 900000) + 100000);
  if (!(await checkRoomExist(roomId))) {
    return roomType === RoomType.Standard ? roomId : `webinar_${roomId}`;
  }
  if (retriesLeft <= 1) {
    const fallbackId = `${Math.floor(Math.random() * 900000) + 100000}_${Date.now()}`;
    return roomType === RoomType.Standard ? fallbackId : `webinar_${fallbackId}`;
  }
  return generateRoomId(roomType, retriesLeft - 1);
};

const handleStartRoom = async (roomType: RoomType) => {
  const roomId = await generateRoomId(roomType);
  sessionStorage.setItem(`room-${roomId}-isCreate`, 'true');
  emit('create-room', roomId, roomType);
};

const handleJoinRoom = async (roomId: string) => {
  if (!roomId) {
    TUIToast.error({ message: t('Room.RoomIdRequired') });
    return;
  }
  if (await checkRoomExist(roomId)) {
    const isWebinar = roomId.startsWith('webinar_');
    emit('join-room', roomId, isWebinar ? RoomType.Webinar : RoomType.Standard);
  } else {
    TUIMessageBox.alert({
      type: 'error',
      modal: false,
      showClose: false,
      title: t('Room.Alert'),
      content: t('Room.RoomNotFound'),
    });
  }
};

const handleScheduleJoinRoom = (roomInfo: { roomId: string }) => {
  handleJoinRoom(roomInfo.roomId);
};

function handleLogout() {
  emit('logout');
}

onMounted(() => {
  const roomPreviewVideo = document.getElementById('room-preview-video');
  TUIRoomEngine.once('ready', async () => {
    if (roomPreviewVideo) {
      try {
        await startCameraTest({ view: roomPreviewVideo as HTMLDivElement });
      } catch (error: any) {
        handleErrorWithModal(error);
      }
    }
    try {
      await startMicrophoneTest();
    } catch (error: any) {
      handleErrorWithModal(error);
    }
  });
});

onBeforeUnmount(() => {
  stopCameraTest();
  stopMicrophoneTest();
});
</script>

<style lang="scss" scoped>
.home-container {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background-color: var(--bg-color-default);
  background-repeat: no-repeat;
  background-size: cover;
}

.dark {
  background-image: url('../../assets/background-black.png');
  .zh-CN.logo {
    background-image: url('../../assets/logo-black-zh.png');
  }
  .en-US.logo {
    background-image: url('../../assets/logo-black-en.png');
  }
}

.light {
  background-image: url('../../assets/background-white.png');
  .zh-CN.logo {
    background-image: url('../../assets/logo-white-zh.png');
  }
  .en-US.logo {
    background-image: url('../../assets/logo-white-en.png');
  }
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 24px;

  &-left {
    display: flex;
    gap: 24px;
    flex: 1;
    justify-content: flex-start;
  }

  &-right {
    display: flex;
    align-items: center;
    gap: 16px;
    flex: 1;
    justify-content: flex-end;
  }
}

.main {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 40px 20px;

  .main-container {
    display: flex;
    flex-direction: row;
    gap: 20px;
  }

  .room-preview-container {
    box-sizing: border-box;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    width: 760px;
    height: 544px;
    padding: 20px 20px 32px;
    border-radius: 24px;
    background-color: var(--bg-color-operate);
    box-shadow:
      0px 2px 6px var(--uikit-color-black-8),
      0px 8px 18px var(--uikit-color-black-8);

    .camera-preview-area {
      width: 100%;
      height: 400px;
      background-color: var(--uikit-color-black-1);
      border-radius: 8px;
      position: relative;
      .video-preview {
        width: 100%;
        height: 100%;
      }
      .attention-info {
        position: absolute;
        top: 0;
        left: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        width: 100%;
        height: 100%;

        .off-camera-info {
          font-size: 22px;
          font-weight: 400;
          line-height: 34px;
          color: var(--uikit-color-gray-7);
        }

        .loading {
          animation: loading-rotate 2s linear infinite;
        }
      }
    }

    .control-container {
      display: flex;
      flex-direction: row;
      justify-content: space-between;

      .media-control-region {
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        gap: 16px;
      }

      .room-control-region {
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        gap: 16px;
      }
    }
  }
}

.title {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 40px;

  .logo {
    width: 484px;
    height: 63px;
    background-repeat: no-repeat;
    background-size: 100%;
  }
}

.logo.en-US {
  width: 352px;
  height: 63px;
  background-repeat: no-repeat;
  background-size: 100%;
}

.video-card {
  background: var(--bg-color-dialog);
  border-radius: 12px;
  padding: 20px;
  box-shadow: var(--shadow-color);
  width: 100%;
  max-width: 360px;
}

.video-area {
  width: 100%;
  height: 200px;
  border-radius: 8px;
  overflow: hidden;
  background: var(--bg-color-input);
  margin-bottom: 16px;

  video {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
}

.controls {
  display: flex;
  justify-content: center;
  gap: 32px;
  margin-bottom: 20px;

  .control-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    cursor: pointer;

    .icon {
      width: 24px;
      height: 24px;
      border-radius: 50%;
      background: var(--bg-color-input);
      margin-bottom: 4px;
      position: relative;

      &.muted,
      &.disabled {
        background: var(--button-color-hangup);
      }

      // 这里可以添加具体的图标样式
      &.audio-icon::before {
        content: '🎤';
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        font-size: 12px;
      }

      &.video-icon::before {
        content: '📹';
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        font-size: 12px;
      }
    }

    span {
      font-size: 12px;
      color: var(--text-color-secondary);
    }
  }
}

.buttons {
  align-items: center;
  height: 48px;
}

.schedule-list {
  min-width: 470px;
  max-width: 470px;
  height: 544px;
  padding: 10px;
  user-select: none;
  border-radius: 24px;
  box-shadow:
    0 2px 6px var(--uikit-color-black-8),
    0 8px 18px var(--uikit-color-black-8);
  background-color: var(--bg-color-operate);
  overflow: auto;
  box-sizing: border-box;

  :deep(::-webkit-scrollbar-track) {
    background: transparent;
    margin: 16px 0;
  }

  :deep(::-webkit-scrollbar) {
    width: 6px;
  }

  :deep(::-webkit-scrollbar-thumb) {
    border-radius: 3px;
    background-color: var(--stroke-color-secondary);
  }
}
</style>

// Web/roomkit/react/RoomKit/views/PreConferenceView/PreviewView.tsx
import { useEffect, useRef } from 'react';
import TUIRoomEngine, { TUIErrorCode } from '@tencentcloud/tuiroom-engine-js';
import {
  IconLoading,
  MessageBox,
  Toast,
  useUIKit,
} from '@tencentcloud/uikit-base-component-react';
import classNames from 'classnames';
import {
  RoomType,
  ScheduledRoomList,
  useDeviceState,
  useRoomModal,
  useRoomState,
} from 'tuikit-atomicx-react/room';
import { CameraButton, JoinRoomButton, LanguageButton, LoginUserInfo, MicButton, ScheduledRoomButton, StartRoomButton, ThemeButton } from '../../components';
import styles from './PreviewView.module.scss';
import type { RoomInfo } from 'tuikit-atomicx-react/room';

const MAX_ROOM_ID_RETRIES = 5;
const PREVIEW_VIDEO_ID = 'room-preview-video';

export interface PreviewViewUIOptions {
  showHeader?: boolean;
  showLogo?: boolean;
}

export interface PreviewViewProps {
  /** Visual options for the preview view chrome. */
  uiOptions?: PreviewViewUIOptions;
  /** Fired when the user clicks "Logout" inside the login info dropdown. */
  onLogout?: () => void;
  /** Fired after a fresh room id is generated for the local user to host. */
  onCreateRoom?: (roomId: string, roomType: RoomType) => void;
  /** Fired after the local user resolves a valid room id to join. */
  onJoinRoom?: (roomId: string, roomType: RoomType) => void;
  /** Fired whenever the camera test starts (`true`) or stops (`false`). */
  onCameraPreferenceChange?: (isOpen: boolean) => void;
  /** Fired whenever the microphone test starts (`true`) or stops (`false`). */
  onMicrophonePreferenceChange?: (isOpen: boolean) => void;
}

export function PreviewView(props: PreviewViewProps) {
  const {
    uiOptions,
    onLogout,
    onCreateRoom,
    onJoinRoom,
    onCameraPreferenceChange,
    onMicrophonePreferenceChange,
  } = props;

  const { t, theme, language } = useUIKit();
  const showHeader = uiOptions?.showHeader ?? true;
  const showLogo = uiOptions?.showLogo ?? true;

  const { getRoomInfo } = useRoomState();
  const {
    isMicrophoneTesting,
    isCameraTesting,
    isCameraTestLoading,
    startCameraTest,
    startMicrophoneTest,
    stopCameraTest,
    stopMicrophoneTest,
  } = useDeviceState();
  const { handleErrorWithModal } = useRoomModal();

  // Latest-ref pattern keeps the watch effects subscribed once while the
  // parent stays free to recreate its callbacks every render.
  const onCameraChangeRef = useRef(onCameraPreferenceChange);
  useEffect(() => {
    onCameraChangeRef.current = onCameraPreferenceChange;
  }, [onCameraPreferenceChange]);

  const onMicChangeRef = useRef(onMicrophonePreferenceChange);
  useEffect(() => {
    onMicChangeRef.current = onMicrophonePreferenceChange;
  }, [onMicrophonePreferenceChange]);

  // Vue's `watch` does not fire on registration; skip the first render to
  // mirror that behaviour and only react to genuine state transitions.
  const isFirstMicWatch = useRef(true);
  useEffect(() => {
    if (isFirstMicWatch.current) {
      isFirstMicWatch.current = false;
      return;
    }
    onMicChangeRef.current?.(isMicrophoneTesting);
  }, [isMicrophoneTesting]);

  const isFirstCameraWatch = useRef(true);
  useEffect(() => {
    if (isFirstCameraWatch.current) {
      isFirstCameraWatch.current = false;
      return;
    }
    onCameraChangeRef.current?.(isCameraTesting);
  }, [isCameraTesting]);

  // onMounted: start camera + microphone tests once the engine reports ready.
  // onBeforeUnmount: tear both tests down.
  useEffect(() => {
    const handleReady = async () => {
      const previewElement = document.getElementById(PREVIEW_VIDEO_ID);
      if (previewElement) {
        try {
          await startCameraTest({ view: previewElement as HTMLDivElement });
        } catch (error) {
          handleErrorWithModal(error as { code?: number; message?: string });
        }
      }
      try {
        await startMicrophoneTest();
      } catch (error) {
        handleErrorWithModal(error as { code?: number; message?: string });
      }
    };

    TUIRoomEngine.once('ready', handleReady);

    return () => {
      stopCameraTest();
      stopMicrophoneTest();
    };
    // The actions returned by useDeviceState/useRoomModal are stable singletons
    // bound at module level in uikit-component-react.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const checkRoomExist = async (roomId: string): Promise<boolean> => {
    try {
      await getRoomInfo({ roomId });
    } catch (error) {
      const err = error as { code?: number };
      if (err.code === TUIErrorCode.ERR_ROOM_ID_NOT_EXIST) {
        return false;
      }
      // Treat any unexpected error (e.g. network) as "room exists" so that
      // generateRoomId retries with a different candidate instead of propagating.
    }
    return true;
  };

  const generateRoomId = async (
    roomType: RoomType,
    retriesLeft = MAX_ROOM_ID_RETRIES,
  ): Promise<string> => {
    const candidate = String(Math.floor(Math.random() * 900000) + 100000);
    if (!(await checkRoomExist(candidate))) {
      return roomType === RoomType.Standard ? candidate : `webinar_${candidate}`;
    }
    if (retriesLeft <= 1) {
      const fallbackId = `${Math.floor(Math.random() * 900000) + 100000}_${Date.now()}`;
      return roomType === RoomType.Standard ? fallbackId : `webinar_${fallbackId}`;
    }
    return generateRoomId(roomType, retriesLeft - 1);
  };

  const handleStartRoom = async (roomType: RoomType) => {
    const roomId = await generateRoomId(roomType);
    sessionStorage.setItem(`room-${roomId}-isCreate`, 'true');
    onCreateRoom?.(roomId, roomType);
  };

  const handleJoinRoom = async (roomId: string) => {
    const normalizedRoomId = roomId.trim();
    if (!normalizedRoomId) {
      Toast.error({ message: t('Room.RoomIdRequired') });
      return;
    }
    if (await checkRoomExist(normalizedRoomId)) {
      const isWebinar = normalizedRoomId.startsWith('webinar_');
      onJoinRoom?.(normalizedRoomId, isWebinar ? RoomType.Webinar : RoomType.Standard);
    } else {
      MessageBox.alert({
        type: 'error',
        modal: false,
        showClose: false,
        title: t('Room.Alert'),
        content: t('Room.RoomNotFound'),
      });
    }
  };

  const handleScheduleJoinRoom = (roomInfo: RoomInfo) => {
    // RoomInfo is already available; call onJoinRoom directly to avoid a redundant API request.
    onJoinRoom?.(roomInfo.roomId, roomInfo.roomType);
  };

  const isDarkTheme = theme === 'dark';
  const isZhLanguage = language === 'zh-CN';
  const themeClass = isDarkTheme ? styles.themeDark : styles.themeLight;
  let logoVariant: string;
  if (isDarkTheme) {
    logoVariant = isZhLanguage ? styles.logoDarkZh : styles.logoDarkEn;
  } else {
    logoVariant = isZhLanguage ? styles.logoLightZh : styles.logoLightEn;
  }

  return (
    <div className={classNames(styles.homeContainer, themeClass)}>
      {showHeader && (
        <header className={styles.header}>
          <div className={styles.headerLeft}>
            <ThemeButton />
          </div>
          <div className={styles.headerRight}>
            <LanguageButton />
            <LoginUserInfo onLogout={onLogout} />
          </div>
        </header>
      )}

      <main className={styles.main}>
        {showLogo && (
          <div className={styles.title}>
            <div className={classNames(styles.logo, logoVariant)} />
          </div>
        )}
        <div className={styles.mainContainer}>
          <div className={styles.roomPreviewContainer}>
            <div className={styles.cameraPreviewArea}>
              <div id={PREVIEW_VIDEO_ID} className={styles.videoPreview} />
              <div className={styles.attentionInfo}>
                {!isCameraTesting && !isCameraTestLoading && (
                  <span className={styles.offCameraInfo}>{t('Off Camera')}</span>
                )}
                {isCameraTestLoading && (
                  <IconLoading size="36" className={styles.loading} />
                )}
              </div>
            </div>
            <div className={styles.controlContainer}>
              <div className={styles.mediaControlRegion}>
                <MicButton />
                <CameraButton cameraTestContainer={PREVIEW_VIDEO_ID} />
              </div>
              <div className={styles.roomControlRegion}>
                <StartRoomButton onStartRoom={handleStartRoom} />
                <JoinRoomButton onJoinRoom={handleJoinRoom} />
                <ScheduledRoomButton />
              </div>
            </div>
          </div>
          <div className={styles.scheduleList}>
            <ScheduledRoomList onJoinRoom={handleScheduleJoinRoom} />
          </div>
        </div>
      </main>
    </div>
  );
}
