// Web/roomkit/vue3/RoomKit/views/ConferenceMainViewH5/index.vue
<template>
  <div id="roomPage" class="room-page">
    <div class="room-container">
      <header :class="['header', { 'toolbar-hidden': !showToolbar }]">
        <div class="header-left">
          <CustomWidgetRenderer zone="top-left" platform="h5">
            <SwitchCameraRegistrarH5 v-if="conference.getWidgetVisible(BuiltinWidget.SwitchCameraWidget)" />
          </CustomWidgetRenderer>
        </div>
        <div class="header-center">
          <CustomWidgetRenderer zone="top-center" platform="h5">
            <CurrentRoomInfoRegistrarH5 v-if="conference.getWidgetVisible(BuiltinWidget.CurrentRoomInfoWidget)" />
          </CustomWidgetRenderer>
        </div>
        <div class="header-right">
          <CustomWidgetRenderer zone="top-right" platform="h5">
            <LeaveRoomRegistrarH5
              v-if="conference.getWidgetVisible(BuiltinWidget.LeaveRoomWidget)"
              @leave="handleLeaveRoom"
              @end="handleEndRoom"
            />
          </CustomWidgetRenderer>
        </div>
      </header>

      <main
        v-tui-loading="{
          visible: isJoiningRoom,
          text: t('Room.EnteringRoom'),
          background: 'transparent',
        }"
        class="room-main"
        @click="toggleToolbar"
      >
        <div
          v-if="conference.getWidgetVisible(BuiltinWidget.RecordingWidget)"
          class="recording-status-anchor"
          :class="{ 'toolbar-visible': showToolbar }"
        >
          <CloudRecordingStatusH5 />
        </div>
        <TUIWatermark
          v-if="watermarkEnabled"
          :font="watermarkFont"
          :content="watermarkContent"
          :gap="watermarkGap"
        >
          <RoomLayoutViewH5>
            <template v-if="$slots['participantViewUI']" #participantViewUI="slotProps">
              <slot name="participantViewUI" v-bind="slotProps" />
            </template>
          </RoomLayoutViewH5>
        </TUIWatermark>
        <RoomLayoutViewH5 v-else>
          <template v-if="$slots['participantViewUI']" #participantViewUI="slotProps">
            <slot name="participantViewUI" v-bind="slotProps" />
          </template>
        </RoomLayoutViewH5>
      </main>

      <footer :class="['room-footer', { 'toolbar-hidden': !showToolbar }]">
        <ExpandFooterH5>
          <CustomWidgetRenderer zone="bottom-center" platform="h5">
            <MemberRegistrarH5 v-if="conference.getWidgetVisible(BuiltinWidget.MemberWidget)" />
            <MicRegistrarH5 v-if="conference.getWidgetVisible(BuiltinWidget.MicWidget)" />
            <CameraRegistrarH5 v-if="conference.getWidgetVisible(BuiltinWidget.CameraWidget)" />
            <InviteRegistrarH5 v-if="conference.getWidgetVisible(BuiltinWidget.InviteWidget) && notWebinar()" />
            <ChatRegistrarH5 v-if="conference.getWidgetVisible(BuiltinWidget.RoomChatWidget) && notWebinar()" />
            <CloudRecordingRegistrarH5 v-if="conference.getWidgetVisible(BuiltinWidget.RecordingWidget) && (isOwner || isAdmin)" />
            <AIToolsRegistrarH5 v-if="conference.getWidgetVisible(BuiltinWidget.AIToolsWidget) && notWebinar()" />
            <SettingsRegistrarH5 v-if="conference.getWidgetVisible(BuiltinWidget.SettingsWidget) && ownerOrNotWebinar()" />
          </CustomWidgetRenderer>
        </ExpandFooterH5>
      </footer>
      <PasswordDialogH5
        v-model="roomPasswordVisible"
        :room-id="joiningRoomId"
        @cancel="handlePasswordCancel"
        @error="handleJoinRoomError"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { watch, onMounted, onUnmounted, computed } from 'vue';
import {
  useUIKit,
  TUIWatermark,
  vTuiLoading,
} from '@tencentcloud/uikit-base-component-vue3';
import {
  useLoginState,
  useRoomState,
  useRoomParticipantState,
  RoomEvent,
  RoomParticipantEvent,
  KickedOutOfRoomReason,
  RoomParticipantRole,
  RoomType,
} from 'tuikit-atomicx-vue3/room';
import { conference } from '../../adapter/conference';
import { RoomEvent as ConferenceRoomEvent, BuiltinWidget } from '../../adapter/type';
import {
  PasswordDialogH5,
  RoomLayoutViewH5,
  ExpandFooterH5,
  CustomWidgetRenderer,
  CloudRecordingStatusH5,
  // Registrar components (H5)
  SwitchCameraRegistrarH5,
  CurrentRoomInfoRegistrarH5,
  LeaveRoomRegistrarH5,
  MemberRegistrarH5,
  MicRegistrarH5,
  CameraRegistrarH5,
  InviteRegistrarH5,
  ChatRegistrarH5,
  SettingsRegistrarH5,
  AIToolsRegistrarH5,
  CloudRecordingRegistrarH5,
} from '../../components';
import useCustomizedAutoPlayDialog from '../../hooks/useCustomizedAutoPlayDialog';
import useRoomLifeCycle from '../../hooks/useRoomLifeCycle';

import { useRoomTips } from '../../hooks/useRoomTips';
import { useRoomToolbarH5 } from '../../hooks/useRoomToolbarH5';
import { eventCenter } from '../../utils/eventCenter';

const { t } = useUIKit();
const { showToolbar, toggleToolbar } = useRoomToolbarH5();

useCustomizedAutoPlayDialog();
useRoomTips();

const { loginUserInfo } = useLoginState();
const { currentRoom } = useRoomState();

const watermarkConfig = computed(() => conference.getFeatureConfig('watermark'));
const watermarkEnabled = computed(() => watermarkConfig.value?.enable !== false);
const watermarkContent = computed(() =>
  watermarkConfig.value?.content ?? [
    loginUserInfo.value?.userName || '',
    loginUserInfo.value?.userId || '',
  ],
);
const watermarkFont = computed(() => watermarkConfig.value?.font ?? { fontSize: 16 });
const watermarkGap = computed<[number, number]>(() => watermarkConfig.value?.gap ?? [0, 100]);
const isWebinar = computed(() => currentRoom.value?.roomType === RoomType.Webinar);

const {
  getParticipantList,
  participantListCursor,
  localParticipant,
  subscribeEvent: subscribeRoomParticipantEvent,
  unsubscribeEvent: unsubscribeRoomParticipantEvent,
} = useRoomParticipantState();
const isOwner = computed(() => localParticipant.value?.role === RoomParticipantRole.Owner);
const isAdmin = computed(() => localParticipant.value?.role === RoomParticipantRole.Admin);
const notWebinar = () => !isWebinar.value;
const ownerOrNotWebinar = () => !isWebinar.value || isOwner.value;
const {
  subscribeEvent: subscribeRoomEvent,
  unsubscribeEvent: unsubscribeRoomEvent,
} = useRoomState();
const {
  isJoiningRoom,
  joiningRoomId,
  roomPasswordVisible,
  handleJoinRoomError,
} = useRoomLifeCycle();

// Cache roomInfo before leave/dismiss since SDK may clear currentRoom after the operation
let cachedRoomInfo: any = null;
watch(() => currentRoom.value, (newRoom) => {
  if (newRoom?.roomId) {
    cachedRoomInfo = { ...newRoom };
  }
}, { immediate: true, deep: true });

const handlePasswordCancel = () => {
  eventCenter.emit(ConferenceRoomEvent.ROOM_ERROR);
};
const handleLeaveRoom = () => {
  eventCenter.emit(ConferenceRoomEvent.ROOM_LEAVE, { roomInfo: cachedRoomInfo || currentRoom.value });
};
const handleEndRoom = () => {
  eventCenter.emit(ConferenceRoomEvent.ROOM_DISMISS, { roomInfo: cachedRoomInfo || currentRoom.value });
};

watch(
  () => currentRoom.value?.roomId,
  async (roomId, oldRoomId) => {
    if (!oldRoomId && roomId) {
      await getParticipantList({ cursor: participantListCursor.value });
    }
  },
  { immediate: true },
);

const onRoomEnded = () => {
  eventCenter.emit(ConferenceRoomEvent.ROOM_DISMISS, { roomInfo: cachedRoomInfo || currentRoom.value });
};
const onKickedFromRoom = (eventInfo: {
  reason: KickedOutOfRoomReason;
  message: string;
}) => {
  eventCenter.emit(ConferenceRoomEvent.KICKED_OUT, {});
};

onMounted(() => {
  subscribeRoomEvent(RoomEvent.onRoomEnded, onRoomEnded);
  subscribeRoomParticipantEvent(
    RoomParticipantEvent.onKickedFromRoom,
    onKickedFromRoom,
  );
});

onUnmounted(() => {
  unsubscribeRoomEvent(RoomEvent.onRoomEnded, onRoomEnded);
  unsubscribeRoomParticipantEvent(
    RoomParticipantEvent.onKickedFromRoom,
    onKickedFromRoom,
  );
});
</script>

<style lang="scss" scoped>
.room-page {
  position: relative;
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: row;
  overflow: hidden;
  font-family:
    -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;

  :deep {
    -webkit-tap-highlight-color: transparent;
  }
}

.room-container {
  width: 100%;
  display: flex;
  flex-direction: column;
  position: relative;
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 8px 16px;
  position: absolute;
  top: 0;
  left: 0;
  z-index: 10;
  width: 100%;
  height: 56px;
  box-sizing: border-box;
  transition: opacity 0.3s, visibility 0.3s;
  background-color: var(--bg-color-bottombar);
  border-bottom: 1px solid var(--stroke-color-secondary);

  &-left {
    flex: 1;
    display: flex;
    gap: 12px;
    justify-content: flex-start;
  }

  &-center {
    flex: 2;
    text-align: center;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  &-right {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: flex-end;
    width: auto;
  }
}

.recording-status-anchor {
  position: absolute;
  top: 16px;
  left: 16px;
  z-index: 2;
  transform: translateY(0);
  transition: transform 0.3s; // matches header transition

  &.toolbar-visible {
    transform: translateY(56px); // header height
  }
}

.room-main {
  min-height: 0;
  width: 100%;
  height: 100%;
  position: absolute;
  left: 0;
  right: 0;
  display: flex;
  background-color: var(--bg-color-topbar);
  user-select: none;

  input,
  textarea,
  [contenteditable='true'] {
    user-select: text;
  }
}

.room-footer {
  position: absolute;
  box-sizing: border-box;
  background-color: var(--bg-color-operate);
  width: 100%;
  height: 90px;
  bottom: 0;
  left: 0;
  transition: opacity 0.3s, visibility 0.3s;
}

.toolbar-hidden {
  visibility: hidden;
  opacity: 0;
  pointer-events: none;
}
</style>

// Web/roomkit/react/RoomKit/views/ConferenceMainViewH5/ConferenceMainViewH5.tsx
import { useEffect, useRef } from 'react';
import type { ReactNode } from 'react';
import {
  IconLoadingSchedule,
  Watermark,
  useUIKit,
} from '@tencentcloud/uikit-base-component-react';
import classNames from 'classnames';
import {
  KickedOutOfRoomReason,
  RoomEvent,
  RoomParticipantEvent,
  RoomParticipantRole,
  RoomType,
  useLoginState,
  useRoomParticipantState,
  useRoomState,
} from 'tuikit-atomicx-react/room';
import { useFeatureConfig } from '../../adapter/conference';
import { RoomEvent as ConferenceRoomEvent } from '../../adapter/type';
import {
  CameraButtonH5,
  ChatButtonH5,
  CloudRecordingButtonH5,
  CloudRecordingStatusH5,
  CurrentRoomInfoH5,
  ExpandFooterH5,
  LeaveRoomButtonH5,
  MemberButtonH5,
  MicButtonH5,
  PasswordDialogH5,
  RoomLayoutViewH5,
  SettingButtonH5,
  SwitchCameraButtonH5,
} from '../../components';
import { useCustomizedAutoPlayDialog } from '../../hooks/useCustomizedAutoPlayDialog';
import { useLoadingFade } from '../../hooks/useLoadingFade';
import useRoomLifeCycle from '../../hooks/useRoomLifeCycle';
import { useRoomTips } from '../../hooks/useRoomTips';
import { useRoomToolbarH5 } from '../../hooks/useRoomToolbarH5';
import { eventCenter } from '../../utils/eventCenter';
import styles from './ConferenceMainViewH5.module.scss';
import type { ParticipantViewSlotPropsH5 } from '../../components';

export interface ConferenceMainViewH5Props {
  /**
   * Render prop for customizing per-participant video tiles. React equivalent
   * of Vue's `<template #participantViewUI>` scoped slot.
   */
  renderParticipantView?: (slotProps: ParticipantViewSlotPropsH5) => ReactNode;
}

export function ConferenceMainViewH5({
  renderParticipantView,
}: ConferenceMainViewH5Props = {}) {
  const { t } = useUIKit();
  const { showToolbar, toggleToolbar } = useRoomToolbarH5();

  useCustomizedAutoPlayDialog();
  useRoomTips();

  const { loginUserInfo } = useLoginState();
  const {
    currentRoom,
    subscribeEvent: subscribeRoomEvent,
    unsubscribeEvent: unsubscribeRoomEvent,
  } = useRoomState();
  const {
    getParticipantList,
    participantListCursor,
    localParticipant,
    subscribeEvent: subscribeRoomParticipantEvent,
    unsubscribeEvent: unsubscribeRoomParticipantEvent,
  } = useRoomParticipantState();
  const {
    isJoiningRoom,
    joiningRoomId,
    roomPasswordVisible,
    setRoomPasswordVisible,
    handleJoinRoomError,
  } = useRoomLifeCycle();
  // Vue H5: v-tui-loading on <main> while isJoiningRoom.
  const { mounted: loadingMounted, active: loadingActive } = useLoadingFade(isJoiningRoom);

  const watermarkConfig = useFeatureConfig('watermark');
  const watermarkEnabled = watermarkConfig?.enable !== false;
  const watermarkContent = watermarkConfig?.content ?? [
    loginUserInfo?.userName || '',
    loginUserInfo?.userId || '',
  ];
  const watermarkFont = watermarkConfig?.font ?? { fontSize: 16 };
  const watermarkGap: [number, number] = watermarkConfig?.gap ?? [0, 100];

  // Widget-visibility flags in Vue live on `conference.getWidgetVisible(...)`,
  // which the React adapter hasn't shipped yet. Registrar / CustomWidgetRenderer
  // is out of scope for the H5 first pass (Vue's `notWebinar()` /
  // `ownerOrNotWebinar()` role gating stays in place), so buttons are wired
  // directly — mirrors the PC-version ConferenceMainView.
  const isWebinar = currentRoom?.roomType === RoomType.Webinar;
  const isOwner = localParticipant?.role === RoomParticipantRole.Owner;
  const isAdmin = localParticipant?.role === RoomParticipantRole.Admin;
  const ownerOrNotWebinar = !isWebinar || isOwner;
  const isOwnerOrAdmin = isOwner || isAdmin;

  // Cache roomInfo before leave/dismiss since SDK may clear currentRoom
  // after the operation. Mirrors Vue's `cachedRoomInfo` deep-watch.
  const cachedRoomInfoRef = useRef<typeof currentRoom | null>(null);
  useEffect(() => {
    if (currentRoom?.roomId) {
      cachedRoomInfoRef.current = { ...currentRoom };
    }
  }, [currentRoom]);

  const handlePasswordCancel = () => {
    eventCenter.emit(ConferenceRoomEvent.ROOM_ERROR);
  };
  const handleLeaveRoom = () => {
    eventCenter.emit(ConferenceRoomEvent.ROOM_LEAVE, {
      roomInfo: cachedRoomInfoRef.current || currentRoom,
    });
  };
  const handleEndRoom = () => {
    eventCenter.emit(ConferenceRoomEvent.ROOM_DISMISS, {
      roomInfo: cachedRoomInfoRef.current || currentRoom,
    });
  };

  // Fetch participant list on first room-join, matching Vue's
  // `watch(() => currentRoom.value?.roomId, ..., { immediate: true })`.
  const participantListCursorRef = useRef(participantListCursor);
  participantListCursorRef.current = participantListCursor;
  const prevRoomIdRef = useRef<string | undefined>(undefined);
  useEffect(() => {
    const roomId = currentRoom?.roomId;
    const oldRoomId = prevRoomIdRef.current;
    prevRoomIdRef.current = roomId;
    if (!oldRoomId && roomId) {
      getParticipantList({ cursor: participantListCursorRef.current });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentRoom?.roomId]);

  useEffect(() => {
    const onRoomEnded = () => {
      eventCenter.emit(ConferenceRoomEvent.ROOM_DISMISS, {
        roomInfo: cachedRoomInfoRef.current || currentRoom,
      });
    };
    const onKickedFromRoom = (_eventInfo: {
      reason: KickedOutOfRoomReason;
      message: string;
    }) => {
      eventCenter.emit(ConferenceRoomEvent.KICKED_OUT, {});
    };
    subscribeRoomEvent(RoomEvent.onRoomEnded, onRoomEnded);
    subscribeRoomParticipantEvent(
      RoomParticipantEvent.onKickedFromRoom,
      onKickedFromRoom,
    );
    return () => {
      unsubscribeRoomEvent(RoomEvent.onRoomEnded, onRoomEnded);
      unsubscribeRoomParticipantEvent(
        RoomParticipantEvent.onKickedFromRoom,
        onKickedFromRoom,
      );
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const layoutSlot = renderParticipantView
    ? (
      <RoomLayoutViewH5 renderParticipantView={renderParticipantView} />
    )
    : (
      <RoomLayoutViewH5 />
    );

  return (
    <div id="roomPage" className={styles.roomPage}>
      <div className={styles.roomContainer}>
        <header
          className={classNames(styles.header, {
            [styles.toolbarHidden]: !showToolbar,
          })}
        >
          <div className={styles.headerLeft}>
            <SwitchCameraButtonH5 />
          </div>
          <div className={styles.headerCenter}>
            <CurrentRoomInfoH5 />
          </div>
          <div className={styles.headerRight}>
            <LeaveRoomButtonH5 onLeave={handleLeaveRoom} onEnd={handleEndRoom} />
          </div>
        </header>

        <main
          className={styles.roomMain}
          onClick={toggleToolbar}
        >
          {loadingMounted && (
            <div
              className={classNames(styles.loadingMask, {
                [styles.loadingMaskActive]: loadingActive,
              })}
              role="alert"
              aria-busy="true"
              aria-live="polite"
              aria-label={t('Room.EnteringRoom')}
            >
              <div className={styles.loadingSpinner}>
                <IconLoadingSchedule
                  className={styles.loadingCircular}
                  size="42px"
                  aria-hidden="true"
                />
                <p className={styles.loadingText}>{t('Room.EnteringRoom')}</p>
              </div>
            </div>
          )}
          <div
            className={classNames(styles.recordingStatusAnchor, {
              [styles.toolbarVisible]: showToolbar,
            })}
          >
            {/* Keep mounted for every role so recording events reach all participants. */}
            <CloudRecordingStatusH5 />
          </div>
          {watermarkEnabled
            ? (
              <Watermark
                font={watermarkFont}
                content={watermarkContent}
                gap={watermarkGap}
              >
                {layoutSlot}
              </Watermark>
            )
            : (
              layoutSlot
            )}
        </main>

        <footer
          className={classNames(styles.roomFooter, {
            [styles.toolbarHidden]: !showToolbar,
          })}
        >
          <ExpandFooterH5>
            <MemberButtonH5 />
            <MicButtonH5 />
            <CameraButtonH5 />
            {/* Chat: hidden in Webinar (matches Vue's `notWebinar()`). */}
            {!isWebinar && <ChatButtonH5 />}
            {/* Recording: owner/admin only. Vue's Registrar checks the same. */}
            {isOwnerOrAdmin && <CloudRecordingButtonH5 />}
            {/* TODO(Day 4): Invite/AI H5 buttons — Webinar hides them too. */}
            {ownerOrNotWebinar && <SettingButtonH5 />}
          </ExpandFooterH5>
        </footer>

        <PasswordDialogH5
          visible={roomPasswordVisible}
          onVisibleChange={setRoomPasswordVisible}
          roomId={joiningRoomId}
          onCancel={handlePasswordCancel}
          onError={handleJoinRoomError}
        />
      </div>
    </div>
  );
}
